# ------------------------------------------------------------------------------
# Script to calculate heritabily estimates males and females of twenty DGRP lines

# ------------------------------------------------------------------------------
# Data generated by Felix P Leiva (e-mail: felixpleiva@gmail.com)
# Script created by Enrico L Rezende (e-mail: )
# Script modified by Felix P Leiva (e-mail: felixpleiva@gmail.com)
# ------------------------------------------------------------------------------
# Cite as:

# Leiva FP, Santos M, Rezende EL, & Verberk WCEP. (2024). Paper data and code
# for: Genetic variation of heat tolerance in a model ectotherm: an approach
# using thermal death times curves. Zenodo. DOI will be available here
# ------------------------------------------------------------------------------
# Cleaning working space
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# ------------------------------------------------------------------------------
# check directory
getwd()
# ------------------------------------------------------------------------------
#Libraries
library(lme4)
library(MuMIn)
library(dplyr)
library(pBrackets)
# ------------------------------------------------------------------------------
#Load data of the 20 DGRP lines
all.lines.21<-read.csv("../Outputs/0.1.1. Survival time of Drosophila melanogaster across DGRP lines.csv")

str(all.lines.21)

#stock as factor
all.lines.21$stock<-as.factor(all.lines.21$stock)

#transform minutes in log10-scale to minutes
all.lines.21$surv.time2<-as.numeric(10^(all.lines.21$surv.time))

# subset by sex
data_f <- subset(all.lines.21, sex == "female") #females
data_m <- subset(all.lines.21, sex == "male") #males
# ------------------------------------------------------------------------------
# Conceptual Figure 1

pdf("../Outputs/2.2.1. Conceptual Figure 1.pdf",width = 6,height = 7,useDingbats = FALSE)
#png("../Outputs/2.2.1. Conceptual Figure 1.png",width = 6,height = 7,units = "in",res = 600)

quartz(,7.5,4)
layout(matrix(c(1,1,2),1,3))
plot(NA,NA,xlim=c(18,45),ylim=c(0,2.2),
     xlab="Temperature (ºC)",
     ylab="Survival time (log10 min)",
     cex.lab=1.3,cex.axis=1.1, las = 1)
segments(20,2,40,1)
segments(20,1,40,0.5)
segments(20,1.5,40,0.75,lty=2)
text(38,1.3,"TDT 1")
text(22,0.8,"TDT 2")
text(42.5,0.75,"pooled")	

m <- anova(lm(c(2,1,1,0.75) ~ c(20,40,20,40)*as.factor(c(0,0,1,1))))	
h2.elevation <- m[2,2]/(m[2,2]+m[3,2])
h2.slope <- m[3,2]/(m[2,2]+m[3,2])
			
plot(NA,NA,xlim=c(0.8,1.8),ylim=c(0,1.5),bty="n",yaxs="i",yaxt="n",xaxt="n",ylab="",xlab="")
text(1.2,1.4,substitute(paste(italic('time =  '),T[a]*"  +  G  +  G*T"[a]*" + "*epsilon)),cex=1.3, xpd=NA)
brackets(1.64,1.35,1.43,1.35,h=0.05)
brackets(1.32,1.35,1.15,1.35,h=0.05)
text(1.25,1.2,substitute(h[e]^2),cex=1.1)
text(1.55,1.2,substitute(h[s]^2),cex=1.1)
	
polygon(c(0.8,0.8,1.2,1.2),c(0,1,1,0))
polygon(c(0.8,0.8,1.2,1.2),c(0,h2.elevation,h2.elevation,0),col="gray")
brackets(1.4,1,1.4,0,h=0.15)
text(1,0.4,substitute(h[e]^2),cex=1.2)
text(1,0.85,substitute(h[s]^2),cex=1.2)
text(1.7,0.5,substitute(h[TDT]^2),cex=1.2)

dev.off()

# ------------------------- Heritability analyses -------------------------------
set.seed(1)

# Heritability males

m.var <- anova(lm(log10(surv.time2) ~ test.temp * genotype, data=data_m))
m.var
m.h2e <- (m.var[2,2])/(m.var[2,2] + m.var[3,2] + m.var[4,2])
m.h2s <- (m.var[3,2])/(m.var[2,2] + m.var[3,2] + m.var[4,2])
m.h2 <- round(m.h2e + m.h2s, 3)
	
# Bootstrap with replacement to calculate heritability sd in males
rep <- 1000
m.out <- matrix(NA,rep,2)
for(i in 1:rep){
var <- anova(lm(log10(surv.time2) ~ test.temp * genotype, data=data_m[sample(1:nrow(data_m),nrow(data_m),replace=TRUE),]))
m.out[i,1] <- (var[2,2])/(var[2,2] + var[3,2] + var[4,2])
m.out[i,2] <- (var[3,2])/(var[2,2] + var[3,2] + var[4,2])}
m.h2e.sd <- sd(m.out[,1]) 
m.h2s.sd <- sd(m.out[,2])
m.h2.sd <- round(sd(m.out[,1] + m.out[,2]),3)
	
		
# Heritability females

f.var <- anova(lm(log10(surv.time2) ~ test.temp * genotype, data=data_f))
f.var
f.h2e <- (f.var[2,2])/(f.var[2,2] + f.var[3,2] + f.var[4,2])
f.h2s <- (f.var[3,2])/(f.var[2,2] + f.var[3,2] + f.var[4,2])	
f.h2 <- round(f.h2e + f.h2s, 3)

# Bootstrap with replacement to calculate heritability sd in females
f.out <- matrix(NA,rep,2)
for(i in 1:rep){
var <- anova(lm(log10(surv.time2) ~ test.temp * genotype, data=data_m[sample(1:nrow(data_f),nrow(data_f),replace=TRUE),]))
f.out[i,1] <- (var[2,2])/(var[2,2] + var[3,2] + var[4,2])
f.out[i,2] <- (var[3,2])/(var[2,2] + var[3,2] + var[4,2])}
f.h2e.sd <- sd(f.out[,1]) 
f.h2s.sd <- sd(f.out[,2])
f.h2.sd <- round(sd(f.out[,1] + f.out[,2]),3)

# ------------------------------------------------------------------------------
# Genetic correlation between males and females
	
m.pred <- predict(lm(log10(surv.time2) ~ test.temp * genotype, data=data_m),
                  newdata=data.frame(test.temp=37.5,genotype=data_m$genotype))
m.mn <- tapply(m.pred,data_m$genotype,mean)

f.pred <- predict(lm(log10(surv.time2) ~ test.temp * genotype, data=data_f),
                  newdata=data.frame(test.temp=37.5,genotype=data_f$genotype))
f.mn <- tapply(f.pred,data_f$genotype,mean)

plot(NA,NA,xlim=c(20,70),ylim=c(20,70), las = 1, 
     xlab="Survival time males (min @ 37.5ºC)",
     ylab="Survival time females (min @ 37.5ºC)")
abline(0,1,lty=2)
points(10^m.mn,10^f.mn,pch=21,cex=1.5,bg="gray")

table(data_f$genotype)
table(data_m$genotype)

cor.test(m.mn,f.mn)

mean(cor(m.mn,f.mn)*sqrt(rowSums(f.out)*rowSums(m.out)))

sd(cor(m.mn,f.mn)*sqrt(rowSums(f.out)*rowSums(m.out)))

#-------------------------------------------------------------------------------
#Felix
table(data_m$genotype)

model_all_lines <- lmer(log10(surv.time2) ~ test.temp + (1 | genotype) + (test.temp | genotype), 
                        data = data_m)

anova(model_all_lines, type=3, ddf="Satterthwaite")

summary(model_all_lines)

# check the estimates of heritability 
m.h2e_ma <- (6.3420/(6.3420 + 6.50004 + 18.6358)) # Mauro
m.h2e_en <- (m.var[2,2])/(m.var[2,2] + m.var[3,2] + m.var[4,2]) # Enrico

m.h2s_ma <- (6.50004/(6.3420 + 6.50004 + 18.6358)) # Mauro
m.h2s_en <- (m.var[3,2])/(m.var[2,2] + m.var[3,2] + m.var[4,2]) # Enrico

m.h2_ma <- round(m.h2e_ma + m.h2s_ma, 3) # Mauro
# [1] 0.408
m.h2_en <- round(m.h2e_en + m.h2s_en, 3) # Enrico
# [1] 0.418
#------------------------------------------------------------------------------

# Assuming 'log10(surv.time2)' is your dependent variable, 'test.temp' is your fixed effect, and 'genotype' is your grouping factor
data_m <- na.omit(data_m)

model_all_lines <- lmer(log10(surv.time2) ~ test.temp + (1 | genotype) + (test.temp | genotype), data = data_m)
summary(model_all_lines)

# Extracting random effects
(original_random_effects <- ranef(model_all_lines)$genotype)
ranef[2,2]
str(original_random_effects)
# Function to compute sum of squares for random effects
sum_of_squares_random_effects <- function(model, grouping_factor) {
  random_effects_genotype <- ranef(model)$genotype
  
  sum((random_effects[[grouping_factor]])^2)
}

# Compute original sum of squares for random effects
original_ss_random_effects <- sum_of_squares_random_effects(model_all_lines, "genotype" ,"genotype:test.temp")

# Create Jackknife Samples and Fit Models
n_levels <- length(levels(data_m$genotype))
jackknife_estimates_random_effects <- numeric(n_levels)

for (i in 1:n_levels) {
  jackknife_data <- data_m[data_m$genotype != levels(data_m$genotype)[i], ]  # Leave out one level of the grouping factor
  jackknife_model <- lmer(log10(surv.time2) ~ test.temp + (1 | genotype) + (test.temp | genotype), data = jackknife_data)
  jackknife_estimates_random_effects[i] <- sum_of_squares_random_effects(jackknife_model, "genotype")
}

# Compute Jackknife Estimate for random effects
jackknife_result_random_effects <- mean(jackknife_estimates_random_effects)

# Display results
cat("Original Sum of Squares for Random Effects: ", original_ss_random_effects, "\n")
cat("Jackknife Estimate of Sum of Squares for Random Effects: ", jackknife_result_random_effects, "\n")
#-------------------------------------------------------------------------------



#saving session information with all package' versions for reproducibility
#purposes
sink("../Outputs/2.1.1. Heritability_TDT_R_session.txt")
sessionInfo()
sink()
################################################################################
############################ END OF SCRIPT #####################################
################################################################################