# ------------------------------------------------------------------------------
# Script to calculate broad-sense heritability (H^2)
# ------------------------------------------------------------------------------
# Data generated by Félix P Leiva (e-mail: felixpleiva@gmail.com) 
# Script created by Félix P Leiva (e-mail: felixpleiva@gmail.com)
# ------------------------------------------------------------------------------
# Cite as:

# Leiva FP, Santos M, Rezende E, & Verberk WCEP. (2022). Data and code of
# manuscript: Genetic variation on heat tolerance in a model ectotherm. Zenodo.
# (DOI is coming)
# ------------------------------------------------------------------------------
# Cleaning working space
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# ------------------------------------------------------------------------------
# set the working directory to the folder containing this script:
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
# ------------------------------------------------------------------------------
# check directory
getwd()
# ------------------------------------------------------------------------------
#Load data for pooled sex
p<-read.csv("../Outputs/1.1.1. Rescaled survival probability of DGRP lines pooled.csv")
#Load data for females
f<-read.csv("../Outputs/1.1.2. Rescaled survival probability of DGRP lines females.csv")
#Load data for males
m<-read.csv("../Outputs/1.1.3. Rescaled survival probability of DGRP lines males.csv")
# ------------------------------------------------------------------------------
# Line as factor
p$Line<-as.factor(p$Line)
f$Line<-as.factor(f$Line)
m$Line<-as.factor(m$Line)
# ------------------------------------------------------------------------------
# Broad-sense heritability across females and females
fit.p<-lm(value~Line,data=p)
summary(fit.p)
anova(fit.p)
round(120505/(120505+343278),3) #genetic variation for pooled sex = 0.26
round(mean(p$value),3) # mean of survival probability for pooled sex
round(sd(p$value)/sqrt(length((p$value))),3) # SE of survival probability for pooled sex

# Broad-sense heritability of females
fit.f<-lm(value~Line,data=f)
summary(fit.f)
anova(fit.f)
round(92843/(92843+148454),3) #genetic variation for females = 0.385
round(mean(f$value),3) # mean of survival probability for females
round(sd(f$value)/sqrt(length((f$value))),3) # SE of survival probability for females

# Broad-sense heritability of males
fit.m<-lm(value~Line,data=m)
summary(fit.m)
anova(fit.m)
round(55410/(55410+136805),3) #genetic variation for males = 0.288
round(mean(m$value),3) # mean of survival probability for males
round(sd(m$value)/sqrt(length((m$value))),3) # SE of survival probability for males
#-------------------------------------------------------------------------------
#saving session information with all packages versions for reproducibility
#purposes
sink("../Outputs/2.1.1. Heritability_TDT_R_session.txt")
sessionInfo()
sink()
################################################################################
############################ END OF SCRIPT #####################################
################################################################################