# ------------------------------------------------------------------------------
# Script to calculate survival probabilities using
# DGRP lines under normoxia (21 kPa)
# ------------------------------------------------------------------------------
# Data generated by Félix P Leiva (e-mail: felixpleiva@gmail.com)
# Script created by Félix P Leiva (e-mail: felixpleiva@gmail.com)
# ------------------------------------------------------------------------------
# Cite as:

# Leiva FP, Santos M, Rezende E, & Verberk WCEP. (2022). Data and code of
# manuscript: Genetic variation on heat tolerance in a model ectotherm. Zenodo.
# (DOI is coming)
# ------------------------------------------------------------------------------
# Cleaning working space
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# ------------------------------------------------------------------------------
# set the working directory to the folder containing this script:
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
# ------------------------------------------------------------------------------
# check directory
getwd()
# ------------------------------------------------------------------------------
#Libraries
library(lme4)
library(MuMIn)
# ------------------------------------------------------------------------------
# Load the function "Thermal landscape functions.R" from the
# paper "Predicting temperature mortality and selection in natural Drosophila
# populations" by Rezende et al 2020 Science 369, (6508) 1242-1245 (10.1126/science.aba9287) 
source("../Functions/Thermal landscape functions.R")
# ------------------------------------------------------------------------------
#Load data of the 20 DGRP lines
all.lines.21<-read.csv("../Outputs/0.1.1. Survival time of Drosophila melanogaster across DGRP lines.csv")

str(all.lines.21)
#stock as factor
all.lines.21$stock<-as.factor(all.lines.21$stock)
#-------------------------------------------------------------------------------
#transform minutes in log10-scale to minutes
all.lines.21$surv.time2<-as.numeric(10^(all.lines.21$surv.time))
#-------------------------------------------------------------------------------
# subset by sex
data_f<-subset(all.lines.21,sex=="female") #females
data_m<-subset(all.lines.21,sex=="male") #males
#-------------------------------------------------------------------------------
# subset by stock
levels(data_f$stock)
# [1] "25180" "25182" "25190" "25192" "25198" "25201" "25203" "28135" "28141" "28153"
# [11] "28173" "28180" "28191" "28196" "28197" "28198" "28247" "28248" "28258" "29652"
#-------------------------------------------------------------------------------
# SEXES POOLED
#-------------------------------------------------------------------------------
p.25180<-subset(all.lines.21,stock=="25180")
p1 <- tolerance.landscape(p.25180$test.temp,p.25180$surv.time2)
p1$Stime_resc<- 10^((1/p1$z)*(p1$ctmax-p1$ta.mn)+ #log time at median Ta
                      log10(p.25180$surv.time2)- #log time observed
                      (1/p1$z)*(p1$ctmax-p.25180$test.temp)) #log time expected

plot(p1$S$time,p1$S$surv,col="red",type="l",ylab="Survival probability",cex.axis=1.2, cex.lab=1.4,xlab="",las=1,xlim=c(0,100))
points((c(98:1)/98)~sort(p1$Stime_resc),col="#00000030")

df.p1<-data.frame(Line=rep("p.25180",each=length(p1$Stime_resc)),
               value=p1$Stime_resc)

p.25182<-subset(all.lines.21,stock=="25182")
p2 <- tolerance.landscape(p.25182$test.temp,p.25182$surv.time2)
p2$Stime_resc<- 10^((1/p2$z)*(p2$ctmax-p2$ta.mn)+ #log time at median Ta
                      log10(p.25182$surv.time2)- #log time observed
                      (1/p2$z)*(p2$ctmax-p.25182$test.temp)) #log time expected
df.p2<-rbind(df.p1,data.frame(Line=rep("p.25182",each=length(p2$Stime_resc)),
                        value=p2$Stime_resc))

p.25190<-subset(all.lines.21,stock=="25190")
p3 <- tolerance.landscape(p.25190$test.temp,p.25190$surv.time2)
p3$Stime_resc<- 10^((1/p3$z)*(p3$ctmax-p3$ta.mn)+ #log time at median Ta
                      log10(p.25190$surv.time2)- #log time observed
                      (1/p3$z)*(p3$ctmax-p.25190$test.temp)) #log time expected
df.p3<-rbind(df.p2,data.frame(Line=rep("p.25190",each=length(p3$Stime_resc)),
                        value=p3$Stime_resc))

p.25192<-subset(all.lines.21,stock=="25192")
p4 <- tolerance.landscape(p.25192$test.temp,p.25192$surv.time2)
p4$Stime_resc<- 10^((1/p4$z)*(p4$ctmax-p4$ta.mn)+ #log time at median Ta
                      log10(p.25192$surv.time2)- #log time observed
                      (1/p4$z)*(p4$ctmax-p.25192$test.temp)) #log time expected
df.p4<-rbind(df.p3,data.frame(Line=rep("p.25192",each=length(p4$Stime_resc)),
                        value=p4$Stime_resc))

p.25198<-subset(all.lines.21,stock=="25198")
p5 <- tolerance.landscape(p.25198$test.temp,p.25198$surv.time2)
p5$Stime_resc<- 10^((1/p5$z)*(p5$ctmax-p5$ta.mn)+ #log time at median Ta
                      log10(p.25198$surv.time2)- #log time observed
                      (1/p5$z)*(p5$ctmax-p.25198$test.temp)) #log time expected
df.p5<-rbind(df.p4,data.frame(Line=rep("p.25198",each=length(p5$Stime_resc)),
                        value=p5$Stime_resc))

p.25201<-subset(all.lines.21,stock=="25201")
p6 <- tolerance.landscape(p.25201$test.temp,p.25201$surv.time2)
p6$Stime_resc<- 10^((1/p6$z)*(p6$ctmax-p6$ta.mn)+ #log time at median Ta
                      log10(p.25201$surv.time2)- #log time observed
                      (1/p6$z)*(p6$ctmax-p.25201$test.temp)) #log time expected
df.p6<-rbind(df.p5,data.frame(Line=rep("p.25201",each=length(p6$Stime_resc)),
                        value=p6$Stime_resc))

p.25203<-subset(all.lines.21,stock=="25203")
p7 <- tolerance.landscape(p.25203$test.temp,p.25203$surv.time2)
p7$Stime_resc<- 10^((1/p7$z)*(p7$ctmax-p7$ta.mn)+ #log time at median Ta
                      log10(p.25203$surv.time2)- #log time observed
                      (1/p7$z)*(p7$ctmax-p.25203$test.temp)) #log time expected
df.p7<-rbind(df.p6,data.frame(Line=rep("p.25203",each=length(p7$Stime_resc)),
                        value=p7$Stime_resc))

p.28135<-subset(all.lines.21,stock=="28135")
p8 <- tolerance.landscape(p.28135$test.temp,p.28135$surv.time2)
p8$Stime_resc<- 10^((1/p8$z)*(p8$ctmax-p8$ta.mn)+ #log time at median Ta
                      log10(p.28135$surv.time2)- #log time observed
                      (1/p8$z)*(p8$ctmax-p.28135$test.temp)) #log time expected
df.p8<-rbind(df.p7,data.frame(Line=rep("p.28135",each=length(p8$Stime_resc)),
                        value=p8$Stime_resc))

p.28141<-subset(all.lines.21,stock=="28141")
p9 <- tolerance.landscape(p.28141$test.temp,p.28141$surv.time2)
p9$Stime_resc<- 10^((1/p9$z)*(p9$ctmax-p9$ta.mn)+ #log time at median Ta
                      log10(p.28141$surv.time2)- #log time observed
                      (1/p9$z)*(p9$ctmax-p.28141$test.temp)) #log time expected
df.p9<-rbind(df.p8,data.frame(Line=rep("p.28141",each=length(p9$Stime_resc)),
                        value=p9$Stime_resc))

p.28153<-subset(all.lines.21,stock=="28153")
p10 <- tolerance.landscape(p.28153$test.temp,p.28153$surv.time2)
p10$Stime_resc<- 10^((1/p10$z)*(p10$ctmax-p10$ta.mn)+ #log time at median Ta
                       log10(p.28153$surv.time2)- #log time observed
                       (1/p10$z)*(p10$ctmax-p.28153$test.temp)) #log time expected
df.p10<-rbind(df.p9,data.frame(Line=rep("p.28153",each=length(p10$Stime_resc)),
                        value=p10$Stime_resc))

p.28173<-subset(all.lines.21,stock=="28173")
p11 <- tolerance.landscape(p.28173$test.temp,p.28173$surv.time2)
p11$Stime_resc<- 10^((1/p11$z)*(p11$ctmax-p5$ta.mn)+ #log time at median Ta
                       log10(p.28173$surv.time2)- #log time observed
                       (1/p11$z)*(p11$ctmax-p.28173$test.temp)) #log time expected
df.p11<-rbind(df.p10,data.frame(Line=rep("p.28173",each=length(p11$Stime_resc)),
                        value=p11$Stime_resc))

p.28180<-subset(all.lines.21,stock=="28180")
p12 <- tolerance.landscape(p.28180$test.temp,p.28180$surv.time2)
p12$Stime_resc<- 10^((1/p12$z)*(p12$ctmax-p12$ta.mn)+ #log time at median Ta
                       log10(p.28180$surv.time2)- #log time observed
                       (1/p12$z)*(p12$ctmax-p.28180$test.temp)) #log time expected
df.p12<-rbind(df.p11,data.frame(Line=rep("p.28180",each=length(p12$Stime_resc)),
                        value=p12$Stime_resc))

p.28191<-subset(all.lines.21,stock=="28191")
p13 <- tolerance.landscape(p.28191$test.temp,p.28191$surv.time2)
p13$Stime_resc<- 10^((1/p13$z)*(p13$ctmax-p13$ta.mn)+ #log time at median Ta
                       log10(p.28191$surv.time2)- #log time observed
                       (1/p13$z)*(p13$ctmax-p.28191$test.temp)) #log time expected
df.p13<-rbind(df.p12,data.frame(Line=rep("p.28191",each=length(p13$Stime_resc)),
                        value=p13$Stime_resc))

p.28196<-subset(all.lines.21,stock=="28196")
p14 <- tolerance.landscape(p.28196$test.temp,p.28196$surv.time2)
p14$Stime_resc<- 10^((1/p14$z)*(p14$ctmax-p14$ta.mn)+ #log time at median Ta
                       log10(p.28196$surv.time2)- #log time observed
                       (1/p14$z)*(p14$ctmax-p.28196$test.temp)) #log time expected
df.p14<-rbind(df.p13,data.frame(Line=rep("p.28196",each=length(p14$Stime_resc)),
                        value=p14$Stime_resc))

p.28197<-subset(all.lines.21,stock=="28197")
p15 <- tolerance.landscape(p.28197$test.temp,p.28197$surv.time2)
p15$Stime_resc<- 10^((1/p15$z)*(p15$ctmax-p15$ta.mn)+ #log time at median Ta
                       log10(p.28197$surv.time2)- #log time observed
                       (1/p15$z)*(p15$ctmax-p.28197$test.temp)) #log time expected
df.p15<-rbind(df.p14,data.frame(Line=rep("p.28197",each=length(p15$Stime_resc)),
                        value=p15$Stime_resc))

p.28198<-subset(all.lines.21,stock=="28198")
p16 <- tolerance.landscape(p.28198$test.temp,p.28198$surv.time2)
p16$Stime_resc<- 10^((1/p16$z)*(p16$ctmax-p16$ta.mn)+ #log time at median Ta
                       log10(p.28198$surv.time2)- #log time observed
                       (1/p16$z)*(p16$ctmax-p.28198$test.temp)) #log time expected
df.p16<-rbind(df.p15,data.frame(Line=rep("p.28198",each=length(p16$Stime_resc)),
                        value=p16$Stime_resc))

p.28247<-subset(all.lines.21,stock=="28247")
p17 <- tolerance.landscape(p.28247$test.temp,p.28247$surv.time2)
p17$Stime_resc<- 10^((1/p17$z)*(p17$ctmax-p17$ta.mn)+ #log time at median Ta
                       log10(p.28247$surv.time2)- #log time observed
                       (1/p17$z)*(p17$ctmax-p.28247$test.temp)) #log time expected
df.p17<-rbind(df.p16,data.frame(Line=rep("p.28247",each=length(p17$Stime_resc)),
                        value=p17$Stime_resc))

p.28248<-subset(all.lines.21,stock=="28248")
p18 <- tolerance.landscape(p.28248$test.temp,p.28248$surv.time2)
p18$Stime_resc<- 10^((1/p18$z)*(p18$ctmax-p18$ta.mn)+ #log time at median Ta
                       log10(p.28248$surv.time2)- #log time observed
                       (1/p18$z)*(p18$ctmax-p.28248$test.temp)) #log time expected
df.p18<-rbind(df.p17,data.frame(Line=rep("p.28248",each=length(p18$Stime_resc)),
                        value=p18$Stime_resc))

p.28258<-subset(all.lines.21,stock=="28258")
p19 <- tolerance.landscape(p.28258$test.temp,p.28258$surv.time2)
p19$Stime_resc<- 10^((1/p19$z)*(p19$ctmax-p19$ta.mn)+ #log time at median Ta
                       log10(p.28258$surv.time2)- #log time observed
                       (1/p19$z)*(p19$ctmax-p.28258$test.temp)) #log time expected
df.p19<-rbind(df.p18,data.frame(Line=rep("p.28258",each=length(p19$Stime_resc)),
                        value=p19$Stime_resc))

p.29652<-subset(all.lines.21,stock=="29652")
p20 <- tolerance.landscape(p.29652$test.temp,p.29652$surv.time2)
p20$Stime_resc<- 10^((1/p20$z)*(p20$ctmax-p20$ta.mn)+ #log time at median Ta
                       log10(p.29652$surv.time2)- #log time observed
                       (1/p20$z)*(p20$ctmax-p.29652$test.temp)) #log time expected
df.p20<-rbind(df.p19,data.frame(Line=rep("p.29652",each=length(p20$Stime_resc)),
                        value=p20$Stime_resc))

pall<-tolerance.landscape(all.lines.21$test.temp,all.lines.21$surv.time2)
pall$Stime_resc<- 10^((1/pall$z)*(pall$ctmax-pall$ta.mn)+ #log time at median Ta
                        log10(all.lines.21$surv.time2)- #log time observed
                        (1/pall$z)*(pall$ctmax-all.lines.21$test.temp)) #log time expected

#-------------------------------------------------------------------------------
# FEMALES
#-------------------------------------------------------------------------------
p.25180<-subset(all.lines.21,stock=="25180")
p1 <- tolerance.landscape(p.25180$test.temp,p.25180$surv.time2)
p1$Stime_resc<- 10^((1/p1$z)*(p1$ctmax-p1$ta.mn)+ #log time at median Ta
                      log10(p.25180$surv.time2)- #log time observed
                      (1/p1$z)*(p1$ctmax-p.25180$test.temp)) #log time expected

plot(p1$S$time,p1$S$surv,col="red",type="l",ylab="Survival probability",cex.axis=1.2, cex.lab=1.4,xlab="",las=1,xlim=c(0,100))
points((c(98:1)/98)~sort(p1$Stime_resc),col="#00000030")

df.p1<-data.frame(Line=rep("p.25180",each=length(p1$Stime_resc)),
                  value=p1$Stime_resc)

p.25182<-subset(all.lines.21,stock=="25182")
p2 <- tolerance.landscape(p.25182$test.temp,p.25182$surv.time2)
p2$Stime_resc<- 10^((1/p2$z)*(p2$ctmax-p2$ta.mn)+ #log time at median Ta
                      log10(p.25182$surv.time2)- #log time observed
                      (1/p2$z)*(p2$ctmax-p.25182$test.temp)) #log time expected
df.p2<-rbind(df.p1,data.frame(Line=rep("p.25182",each=length(p2$Stime_resc)),
                              value=p2$Stime_resc))

p.25190<-subset(all.lines.21,stock=="25190")
p3 <- tolerance.landscape(p.25190$test.temp,p.25190$surv.time2)
p3$Stime_resc<- 10^((1/p3$z)*(p3$ctmax-p3$ta.mn)+ #log time at median Ta
                      log10(p.25190$surv.time2)- #log time observed
                      (1/p3$z)*(p3$ctmax-p.25190$test.temp)) #log time expected
df.p3<-rbind(df.p2,data.frame(Line=rep("p.25190",each=length(p3$Stime_resc)),
                              value=p3$Stime_resc))

p.25192<-subset(all.lines.21,stock=="25192")
p4 <- tolerance.landscape(p.25192$test.temp,p.25192$surv.time2)
p4$Stime_resc<- 10^((1/p4$z)*(p4$ctmax-p4$ta.mn)+ #log time at median Ta
                      log10(p.25192$surv.time2)- #log time observed
                      (1/p4$z)*(p4$ctmax-p.25192$test.temp)) #log time expected
df.p4<-rbind(df.p3,data.frame(Line=rep("p.25192",each=length(p4$Stime_resc)),
                              value=p4$Stime_resc))

p.25198<-subset(all.lines.21,stock=="25198")
p5 <- tolerance.landscape(p.25198$test.temp,p.25198$surv.time2)
p5$Stime_resc<- 10^((1/p5$z)*(p5$ctmax-p5$ta.mn)+ #log time at median Ta
                      log10(p.25198$surv.time2)- #log time observed
                      (1/p5$z)*(p5$ctmax-p.25198$test.temp)) #log time expected
df.p5<-rbind(df.p4,data.frame(Line=rep("p.25198",each=length(p5$Stime_resc)),
                              value=p5$Stime_resc))

p.25201<-subset(all.lines.21,stock=="25201")
p6 <- tolerance.landscape(p.25201$test.temp,p.25201$surv.time2)
p6$Stime_resc<- 10^((1/p6$z)*(p6$ctmax-p6$ta.mn)+ #log time at median Ta
                      log10(p.25201$surv.time2)- #log time observed
                      (1/p6$z)*(p6$ctmax-p.25201$test.temp)) #log time expected
df.p6<-rbind(df.p5,data.frame(Line=rep("p.25201",each=length(p6$Stime_resc)),
                              value=p6$Stime_resc))

p.25203<-subset(all.lines.21,stock=="25203")
p7 <- tolerance.landscape(p.25203$test.temp,p.25203$surv.time2)
p7$Stime_resc<- 10^((1/p7$z)*(p7$ctmax-p7$ta.mn)+ #log time at median Ta
                      log10(p.25203$surv.time2)- #log time observed
                      (1/p7$z)*(p7$ctmax-p.25203$test.temp)) #log time expected
df.p7<-rbind(df.p6,data.frame(Line=rep("p.25203",each=length(p7$Stime_resc)),
                              value=p7$Stime_resc))

p.28135<-subset(all.lines.21,stock=="28135")
p8 <- tolerance.landscape(p.28135$test.temp,p.28135$surv.time2)
p8$Stime_resc<- 10^((1/p8$z)*(p8$ctmax-p8$ta.mn)+ #log time at median Ta
                      log10(p.28135$surv.time2)- #log time observed
                      (1/p8$z)*(p8$ctmax-p.28135$test.temp)) #log time expected
df.p8<-rbind(df.p7,data.frame(Line=rep("p.28135",each=length(p8$Stime_resc)),
                              value=p8$Stime_resc))

p.28141<-subset(all.lines.21,stock=="28141")
p9 <- tolerance.landscape(p.28141$test.temp,p.28141$surv.time2)
p9$Stime_resc<- 10^((1/p9$z)*(p9$ctmax-p9$ta.mn)+ #log time at median Ta
                      log10(p.28141$surv.time2)- #log time observed
                      (1/p9$z)*(p9$ctmax-p.28141$test.temp)) #log time expected
df.p9<-rbind(df.p8,data.frame(Line=rep("p.28141",each=length(p9$Stime_resc)),
                              value=p9$Stime_resc))

p.28153<-subset(all.lines.21,stock=="28153")
p10 <- tolerance.landscape(p.28153$test.temp,p.28153$surv.time2)
p10$Stime_resc<- 10^((1/p10$z)*(p10$ctmax-p10$ta.mn)+ #log time at median Ta
                       log10(p.28153$surv.time2)- #log time observed
                       (1/p10$z)*(p10$ctmax-p.28153$test.temp)) #log time expected
df.p10<-rbind(df.p9,data.frame(Line=rep("p.28153",each=length(p10$Stime_resc)),
                               value=p10$Stime_resc))

p.28173<-subset(all.lines.21,stock=="28173")
p11 <- tolerance.landscape(p.28173$test.temp,p.28173$surv.time2)
p11$Stime_resc<- 10^((1/p11$z)*(p11$ctmax-p5$ta.mn)+ #log time at median Ta
                       log10(p.28173$surv.time2)- #log time observed
                       (1/p11$z)*(p11$ctmax-p.28173$test.temp)) #log time expected
df.p11<-rbind(df.p10,data.frame(Line=rep("p.28173",each=length(p11$Stime_resc)),
                                value=p11$Stime_resc))

p.28180<-subset(all.lines.21,stock=="28180")
p12 <- tolerance.landscape(p.28180$test.temp,p.28180$surv.time2)
p12$Stime_resc<- 10^((1/p12$z)*(p12$ctmax-p12$ta.mn)+ #log time at median Ta
                       log10(p.28180$surv.time2)- #log time observed
                       (1/p12$z)*(p12$ctmax-p.28180$test.temp)) #log time expected
df.p12<-rbind(df.p11,data.frame(Line=rep("p.28180",each=length(p12$Stime_resc)),
                                value=p12$Stime_resc))

p.28191<-subset(all.lines.21,stock=="28191")
p13 <- tolerance.landscape(p.28191$test.temp,p.28191$surv.time2)
p13$Stime_resc<- 10^((1/p13$z)*(p13$ctmax-p13$ta.mn)+ #log time at median Ta
                       log10(p.28191$surv.time2)- #log time observed
                       (1/p13$z)*(p13$ctmax-p.28191$test.temp)) #log time expected
df.p13<-rbind(df.p12,data.frame(Line=rep("p.28191",each=length(p13$Stime_resc)),
                                value=p13$Stime_resc))

p.28196<-subset(all.lines.21,stock=="28196")
p14 <- tolerance.landscape(p.28196$test.temp,p.28196$surv.time2)
p14$Stime_resc<- 10^((1/p14$z)*(p14$ctmax-p14$ta.mn)+ #log time at median Ta
                       log10(p.28196$surv.time2)- #log time observed
                       (1/p14$z)*(p14$ctmax-p.28196$test.temp)) #log time expected
df.p14<-rbind(df.p13,data.frame(Line=rep("p.28196",each=length(p14$Stime_resc)),
                                value=p14$Stime_resc))

p.28197<-subset(all.lines.21,stock=="28197")
p15 <- tolerance.landscape(p.28197$test.temp,p.28197$surv.time2)
p15$Stime_resc<- 10^((1/p15$z)*(p15$ctmax-p15$ta.mn)+ #log time at median Ta
                       log10(p.28197$surv.time2)- #log time observed
                       (1/p15$z)*(p15$ctmax-p.28197$test.temp)) #log time expected
df.p15<-rbind(df.p14,data.frame(Line=rep("p.28197",each=length(p15$Stime_resc)),
                                value=p15$Stime_resc))

p.28198<-subset(all.lines.21,stock=="28198")
p16 <- tolerance.landscape(p.28198$test.temp,p.28198$surv.time2)
p16$Stime_resc<- 10^((1/p16$z)*(p16$ctmax-p16$ta.mn)+ #log time at median Ta
                       log10(p.28198$surv.time2)- #log time observed
                       (1/p16$z)*(p16$ctmax-p.28198$test.temp)) #log time expected
df.p16<-rbind(df.p15,data.frame(Line=rep("p.28198",each=length(p16$Stime_resc)),
                                value=p16$Stime_resc))

p.28247<-subset(all.lines.21,stock=="28247")
p17 <- tolerance.landscape(p.28247$test.temp,p.28247$surv.time2)
p17$Stime_resc<- 10^((1/p17$z)*(p17$ctmax-p17$ta.mn)+ #log time at median Ta
                       log10(p.28247$surv.time2)- #log time observed
                       (1/p17$z)*(p17$ctmax-p.28247$test.temp)) #log time expected
df.p17<-rbind(df.p16,data.frame(Line=rep("p.28247",each=length(p17$Stime_resc)),
                                value=p17$Stime_resc))

p.28248<-subset(all.lines.21,stock=="28248")
p18 <- tolerance.landscape(p.28248$test.temp,p.28248$surv.time2)
p18$Stime_resc<- 10^((1/p18$z)*(p18$ctmax-p18$ta.mn)+ #log time at median Ta
                       log10(p.28248$surv.time2)- #log time observed
                       (1/p18$z)*(p18$ctmax-p.28248$test.temp)) #log time expected
df.p18<-rbind(df.p17,data.frame(Line=rep("p.28248",each=length(p18$Stime_resc)),
                                value=p18$Stime_resc))

p.28258<-subset(all.lines.21,stock=="28258")
p19 <- tolerance.landscape(p.28258$test.temp,p.28258$surv.time2)
p19$Stime_resc<- 10^((1/p19$z)*(p19$ctmax-p19$ta.mn)+ #log time at median Ta
                       log10(p.28258$surv.time2)- #log time observed
                       (1/p19$z)*(p19$ctmax-p.28258$test.temp)) #log time expected
df.p19<-rbind(df.p18,data.frame(Line=rep("p.28258",each=length(p19$Stime_resc)),
                                value=p19$Stime_resc))

p.29652<-subset(all.lines.21,stock=="29652")
p20 <- tolerance.landscape(p.29652$test.temp,p.29652$surv.time2)
p20$Stime_resc<- 10^((1/p20$z)*(p20$ctmax-p20$ta.mn)+ #log time at median Ta
                       log10(p.29652$surv.time2)- #log time observed
                       (1/p20$z)*(p20$ctmax-p.29652$test.temp)) #log time expected
df.p20<-rbind(df.p19,data.frame(Line=rep("p.29652",each=length(p20$Stime_resc)),
                                value=p20$Stime_resc))

pall<-tolerance.landscape(all.lines.21$test.temp,all.lines.21$surv.time2)
pall$Stime_resc<- 10^((1/pall$z)*(pall$ctmax-pall$ta.mn)+ #log time at median Ta
                        log10(all.lines.21$surv.time2)- #log time observed
                        (1/pall$z)*(pall$ctmax-all.lines.21$test.temp)) #log time expected

#-------------------------------------------------------------------------------
# MALES
#-------------------------------------------------------------------------------
p.25180<-subset(all.lines.21,stock=="25180")
p1 <- tolerance.landscape(p.25180$test.temp,p.25180$surv.time2)
p1$Stime_resc<- 10^((1/p1$z)*(p1$ctmax-p1$ta.mn)+ #log time at median Ta
                      log10(p.25180$surv.time2)- #log time observed
                      (1/p1$z)*(p1$ctmax-p.25180$test.temp)) #log time expected

plot(p1$S$time,p1$S$surv,col="red",type="l",ylab="Survival probability",cex.axis=1.2, cex.lab=1.4,xlab="",las=1,xlim=c(0,100))
points((c(98:1)/98)~sort(p1$Stime_resc),col="#00000030")

df.p1<-data.frame(Line=rep("p.25180",each=length(p1$Stime_resc)),
                  value=p1$Stime_resc)

p.25182<-subset(all.lines.21,stock=="25182")
p2 <- tolerance.landscape(p.25182$test.temp,p.25182$surv.time2)
p2$Stime_resc<- 10^((1/p2$z)*(p2$ctmax-p2$ta.mn)+ #log time at median Ta
                      log10(p.25182$surv.time2)- #log time observed
                      (1/p2$z)*(p2$ctmax-p.25182$test.temp)) #log time expected
df.p2<-rbind(df.p1,data.frame(Line=rep("p.25182",each=length(p2$Stime_resc)),
                              value=p2$Stime_resc))

p.25190<-subset(all.lines.21,stock=="25190")
p3 <- tolerance.landscape(p.25190$test.temp,p.25190$surv.time2)
p3$Stime_resc<- 10^((1/p3$z)*(p3$ctmax-p3$ta.mn)+ #log time at median Ta
                      log10(p.25190$surv.time2)- #log time observed
                      (1/p3$z)*(p3$ctmax-p.25190$test.temp)) #log time expected
df.p3<-rbind(df.p2,data.frame(Line=rep("p.25190",each=length(p3$Stime_resc)),
                              value=p3$Stime_resc))

p.25192<-subset(all.lines.21,stock=="25192")
p4 <- tolerance.landscape(p.25192$test.temp,p.25192$surv.time2)
p4$Stime_resc<- 10^((1/p4$z)*(p4$ctmax-p4$ta.mn)+ #log time at median Ta
                      log10(p.25192$surv.time2)- #log time observed
                      (1/p4$z)*(p4$ctmax-p.25192$test.temp)) #log time expected
df.p4<-rbind(df.p3,data.frame(Line=rep("p.25192",each=length(p4$Stime_resc)),
                              value=p4$Stime_resc))

p.25198<-subset(all.lines.21,stock=="25198")
p5 <- tolerance.landscape(p.25198$test.temp,p.25198$surv.time2)
p5$Stime_resc<- 10^((1/p5$z)*(p5$ctmax-p5$ta.mn)+ #log time at median Ta
                      log10(p.25198$surv.time2)- #log time observed
                      (1/p5$z)*(p5$ctmax-p.25198$test.temp)) #log time expected
df.p5<-rbind(df.p4,data.frame(Line=rep("p.25198",each=length(p5$Stime_resc)),
                              value=p5$Stime_resc))

p.25201<-subset(all.lines.21,stock=="25201")
p6 <- tolerance.landscape(p.25201$test.temp,p.25201$surv.time2)
p6$Stime_resc<- 10^((1/p6$z)*(p6$ctmax-p6$ta.mn)+ #log time at median Ta
                      log10(p.25201$surv.time2)- #log time observed
                      (1/p6$z)*(p6$ctmax-p.25201$test.temp)) #log time expected
df.p6<-rbind(df.p5,data.frame(Line=rep("p.25201",each=length(p6$Stime_resc)),
                              value=p6$Stime_resc))

p.25203<-subset(all.lines.21,stock=="25203")
p7 <- tolerance.landscape(p.25203$test.temp,p.25203$surv.time2)
p7$Stime_resc<- 10^((1/p7$z)*(p7$ctmax-p7$ta.mn)+ #log time at median Ta
                      log10(p.25203$surv.time2)- #log time observed
                      (1/p7$z)*(p7$ctmax-p.25203$test.temp)) #log time expected
df.p7<-rbind(df.p6,data.frame(Line=rep("p.25203",each=length(p7$Stime_resc)),
                              value=p7$Stime_resc))

p.28135<-subset(all.lines.21,stock=="28135")
p8 <- tolerance.landscape(p.28135$test.temp,p.28135$surv.time2)
p8$Stime_resc<- 10^((1/p8$z)*(p8$ctmax-p8$ta.mn)+ #log time at median Ta
                      log10(p.28135$surv.time2)- #log time observed
                      (1/p8$z)*(p8$ctmax-p.28135$test.temp)) #log time expected
df.p8<-rbind(df.p7,data.frame(Line=rep("p.28135",each=length(p8$Stime_resc)),
                              value=p8$Stime_resc))

p.28141<-subset(all.lines.21,stock=="28141")
p9 <- tolerance.landscape(p.28141$test.temp,p.28141$surv.time2)
p9$Stime_resc<- 10^((1/p9$z)*(p9$ctmax-p9$ta.mn)+ #log time at median Ta
                      log10(p.28141$surv.time2)- #log time observed
                      (1/p9$z)*(p9$ctmax-p.28141$test.temp)) #log time expected
df.p9<-rbind(df.p8,data.frame(Line=rep("p.28141",each=length(p9$Stime_resc)),
                              value=p9$Stime_resc))

p.28153<-subset(all.lines.21,stock=="28153")
p10 <- tolerance.landscape(p.28153$test.temp,p.28153$surv.time2)
p10$Stime_resc<- 10^((1/p10$z)*(p10$ctmax-p10$ta.mn)+ #log time at median Ta
                       log10(p.28153$surv.time2)- #log time observed
                       (1/p10$z)*(p10$ctmax-p.28153$test.temp)) #log time expected
df.p10<-rbind(df.p9,data.frame(Line=rep("p.28153",each=length(p10$Stime_resc)),
                               value=p10$Stime_resc))

p.28173<-subset(all.lines.21,stock=="28173")
p11 <- tolerance.landscape(p.28173$test.temp,p.28173$surv.time2)
p11$Stime_resc<- 10^((1/p11$z)*(p11$ctmax-p5$ta.mn)+ #log time at median Ta
                       log10(p.28173$surv.time2)- #log time observed
                       (1/p11$z)*(p11$ctmax-p.28173$test.temp)) #log time expected
df.p11<-rbind(df.p10,data.frame(Line=rep("p.28173",each=length(p11$Stime_resc)),
                                value=p11$Stime_resc))

p.28180<-subset(all.lines.21,stock=="28180")
p12 <- tolerance.landscape(p.28180$test.temp,p.28180$surv.time2)
p12$Stime_resc<- 10^((1/p12$z)*(p12$ctmax-p12$ta.mn)+ #log time at median Ta
                       log10(p.28180$surv.time2)- #log time observed
                       (1/p12$z)*(p12$ctmax-p.28180$test.temp)) #log time expected
df.p12<-rbind(df.p11,data.frame(Line=rep("p.28180",each=length(p12$Stime_resc)),
                                value=p12$Stime_resc))

p.28191<-subset(all.lines.21,stock=="28191")
p13 <- tolerance.landscape(p.28191$test.temp,p.28191$surv.time2)
p13$Stime_resc<- 10^((1/p13$z)*(p13$ctmax-p13$ta.mn)+ #log time at median Ta
                       log10(p.28191$surv.time2)- #log time observed
                       (1/p13$z)*(p13$ctmax-p.28191$test.temp)) #log time expected
df.p13<-rbind(df.p12,data.frame(Line=rep("p.28191",each=length(p13$Stime_resc)),
                                value=p13$Stime_resc))

p.28196<-subset(all.lines.21,stock=="28196")
p14 <- tolerance.landscape(p.28196$test.temp,p.28196$surv.time2)
p14$Stime_resc<- 10^((1/p14$z)*(p14$ctmax-p14$ta.mn)+ #log time at median Ta
                       log10(p.28196$surv.time2)- #log time observed
                       (1/p14$z)*(p14$ctmax-p.28196$test.temp)) #log time expected
df.p14<-rbind(df.p13,data.frame(Line=rep("p.28196",each=length(p14$Stime_resc)),
                                value=p14$Stime_resc))

p.28197<-subset(all.lines.21,stock=="28197")
p15 <- tolerance.landscape(p.28197$test.temp,p.28197$surv.time2)
p15$Stime_resc<- 10^((1/p15$z)*(p15$ctmax-p15$ta.mn)+ #log time at median Ta
                       log10(p.28197$surv.time2)- #log time observed
                       (1/p15$z)*(p15$ctmax-p.28197$test.temp)) #log time expected
df.p15<-rbind(df.p14,data.frame(Line=rep("p.28197",each=length(p15$Stime_resc)),
                                value=p15$Stime_resc))

p.28198<-subset(all.lines.21,stock=="28198")
p16 <- tolerance.landscape(p.28198$test.temp,p.28198$surv.time2)
p16$Stime_resc<- 10^((1/p16$z)*(p16$ctmax-p16$ta.mn)+ #log time at median Ta
                       log10(p.28198$surv.time2)- #log time observed
                       (1/p16$z)*(p16$ctmax-p.28198$test.temp)) #log time expected
df.p16<-rbind(df.p15,data.frame(Line=rep("p.28198",each=length(p16$Stime_resc)),
                                value=p16$Stime_resc))

p.28247<-subset(all.lines.21,stock=="28247")
p17 <- tolerance.landscape(p.28247$test.temp,p.28247$surv.time2)
p17$Stime_resc<- 10^((1/p17$z)*(p17$ctmax-p17$ta.mn)+ #log time at median Ta
                       log10(p.28247$surv.time2)- #log time observed
                       (1/p17$z)*(p17$ctmax-p.28247$test.temp)) #log time expected
df.p17<-rbind(df.p16,data.frame(Line=rep("p.28247",each=length(p17$Stime_resc)),
                                value=p17$Stime_resc))

p.28248<-subset(all.lines.21,stock=="28248")
p18 <- tolerance.landscape(p.28248$test.temp,p.28248$surv.time2)
p18$Stime_resc<- 10^((1/p18$z)*(p18$ctmax-p18$ta.mn)+ #log time at median Ta
                       log10(p.28248$surv.time2)- #log time observed
                       (1/p18$z)*(p18$ctmax-p.28248$test.temp)) #log time expected
df.p18<-rbind(df.p17,data.frame(Line=rep("p.28248",each=length(p18$Stime_resc)),
                                value=p18$Stime_resc))

p.28258<-subset(all.lines.21,stock=="28258")
p19 <- tolerance.landscape(p.28258$test.temp,p.28258$surv.time2)
p19$Stime_resc<- 10^((1/p19$z)*(p19$ctmax-p19$ta.mn)+ #log time at median Ta
                       log10(p.28258$surv.time2)- #log time observed
                       (1/p19$z)*(p19$ctmax-p.28258$test.temp)) #log time expected
df.p19<-rbind(df.p18,data.frame(Line=rep("p.28258",each=length(p19$Stime_resc)),
                                value=p19$Stime_resc))

p.29652<-subset(all.lines.21,stock=="29652")
p20 <- tolerance.landscape(p.29652$test.temp,p.29652$surv.time2)
p20$Stime_resc<- 10^((1/p20$z)*(p20$ctmax-p20$ta.mn)+ #log time at median Ta
                       log10(p.29652$surv.time2)- #log time observed
                       (1/p20$z)*(p20$ctmax-p.29652$test.temp)) #log time expected
df.p20<-rbind(df.p19,data.frame(Line=rep("p.29652",each=length(p20$Stime_resc)),
                                value=p20$Stime_resc))

pall<-tolerance.landscape(all.lines.21$test.temp,all.lines.21$surv.time2)
pall$Stime_resc<- 10^((1/pall$z)*(pall$ctmax-pall$ta.mn)+ #log time at median Ta
                        log10(all.lines.21$surv.time2)- #log time observed
                        (1/pall$z)*(pall$ctmax-all.lines.21$test.temp)) #log time expected

#-------------------------------------------------------------------------------
# FIGURE 1
#-------------------------------------------------------------------------------
{
  pdf("Figure 1 Survival probabilities of DGRP lines.pdf",width = 6,height = 8,useDingbats = FALSE)
  #png("Figure 1 Survival probabilities of DGRP lines.png",width = 6,height = 8,units = "in",res = 600)
  par(mfrow=c(3,2),tcl=-0.4, family="serif",omi=c(0,0,0,0))
  
  #Sexes pooled
  # labels
  labs= c("1","2","5","10","30","120","420")
  xs= log10(c(1,2,5,10,30,60*2,60*7))
  
  par(mai=c(0.55,0.6,0.1,0.1))
  plot(surv.time ~ jitter(test.temp,0.5),xlim=c(35.6,39.4),ylim=c(0,3),cex.axis=1.2, 
       cex.lab=1.4,yaxt="n",cex=1.4,pch=16,col="#55555540",xlab="",ylab="Time (min)",data=p.25180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25182)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25190)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25192)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25201)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25203)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28135)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28141)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28153)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28173)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28191)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28196)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28197)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28247)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28248)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28258)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.29652)
  abline(lm(surv.time ~ test.temp,data = p.25180),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25182),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25190),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25192),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25198),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25201),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25203),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28135),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28141),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28153),col="gray")	
  abline(lm(surv.time ~ test.temp,data = p.28173),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28180),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28191),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28196),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28197),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28198),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28247),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28248),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28258),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.29652),col="gray")
  abline(lm(surv.time ~ test.temp,data = all.lines.21),col="#555555",lwd=3)
  
  #update axis
  axis(2, at=xs, labels=labs, cex.axis=1.2)
  par(mai=c(0.55,0.6,0.1,0.1))
  
  
  plot(sort(p1$Stime_resc),rev(100*(1:length(p1$Stime_resc)-1)/(length(p1$Stime_resc)-1)),
       col="gray",type="l",ylab="Survival probability",cex.axis=1.2, cex.lab=1.4,xlab="",las=1,xlim=c(0,105))
  points(sort(p2$Stime_resc),rev(100*(1:length(p2$Stime_resc)-1)/(length(p2$Stime_resc)-1)),col="gray",type="l")
  points(sort(p3$Stime_resc),rev(100*(1:length(p3$Stime_resc)-1)/(length(p3$Stime_resc)-1)),col="gray",type="l")
  points(sort(p4$Stime_resc),rev(100*(1:length(p4$Stime_resc)-1)/(length(p4$Stime_resc)-1)),col="gray",type="l")
  points(sort(p5$Stime_resc),rev(100*(1:length(p5$Stime_resc)-1)/(length(p5$Stime_resc)-1)),col="gray",type="l")
  points(sort(p6$Stime_resc),rev(100*(1:length(p6$Stime_resc)-1)/(length(p6$Stime_resc)-1)),col="gray",type="l")
  points(sort(p7$Stime_resc),rev(100*(1:length(p7$Stime_resc)-1)/(length(p7$Stime_resc)-1)),col="gray",type="l")
  points(sort(p8$Stime_resc),rev(100*(1:length(p8$Stime_resc)-1)/(length(p8$Stime_resc)-1)),col="gray",type="l")
  points(sort(p9$Stime_resc),rev(100*(1:length(p9$Stime_resc)-1)/(length(p9$Stime_resc)-1)),col="gray",type="l")
  points(sort(p10$Stime_resc),rev(100*(1:length(p10$Stime_resc)-1)/(length(p10$Stime_resc)-1)),col="gray",type="l")
  points(sort(p11$Stime_resc),rev(100*(1:length(p11$Stime_resc)-1)/(length(p11$Stime_resc)-1)),col="gray",type="l")
  points(sort(p12$Stime_resc),rev(100*(1:length(p12$Stime_resc)-1)/(length(p12$Stime_resc)-1)),col="gray",type="l")
  points(sort(p13$Stime_resc),rev(100*(1:length(p13$Stime_resc)-1)/(length(p13$Stime_resc)-1)),col="gray",type="l")
  points(sort(p14$Stime_resc),rev(100*(1:length(p14$Stime_resc)-1)/(length(p14$Stime_resc)-1)),col="gray",type="l")
  points(sort(p15$Stime_resc),rev(100*(1:length(p15$Stime_resc)-1)/(length(p15$Stime_resc)-1)),col="gray",type="l")
  points(sort(p16$Stime_resc),rev(100*(1:length(p16$Stime_resc)-1)/(length(p16$Stime_resc)-1)),col="gray",type="l")
  points(sort(p17$Stime_resc),rev(100*(1:length(p17$Stime_resc)-1)/(length(p17$Stime_resc)-1)),col="gray",type="l")
  points(sort(p18$Stime_resc),rev(100*(1:length(p18$Stime_resc)-1)/(length(p18$Stime_resc)-1)),col="gray",type="l")
  points(sort(p19$Stime_resc),rev(100*(1:length(p19$Stime_resc)-1)/(length(p19$Stime_resc)-1)),col="gray",type="l")
  points(sort(p20$Stime_resc),rev(100*(1:length(p20$Stime_resc)-1)/(length(p20$Stime_resc)-1)),col="gray",type="l")
  points(sort(pall$Stime_resc),rev(100*(1:length(pall$Stime_resc)-1)/(length(pall$Stime_resc)-1)),col="#555555",lwd=3,type="l")
  text(70,92,"Inbred lines",col="gray",adj=0,font=2,cex=1.2)
  text(70,85,"Pooled lines",adj=0,col="#555555",font=2,cex=1.2)
  
  #-----------------------------------------------------------------------------
  #females
  # labels
  labs= c("1","2","5","10","30","120","420")
  xs= log10(c(1,2,5,10,30,60*2,60*7))
  
  par(mai=c(0.55,0.6,0,0.1))
  plot(surv.time ~ jitter(test.temp,0.5),xlim=c(35.6,39.4),ylim=c(0,3),cex.axis=1.2, cex.lab=1.4,yaxt="n",cex=1.4,pch=16,col="#4DAC2660",xlab="",ylab="Time (min)",data=f.25180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25182)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25190)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25192)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25201)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25203)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28135)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28141)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28153)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28173)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28191)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28196)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28197)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28247)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28248)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28258)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.29652)
  abline(lm(surv.time ~ test.temp,data = f.25180),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25182),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25190),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25192),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25198),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25201),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25203),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28135),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28141),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28153),col="gray")	
  abline(lm(surv.time ~ test.temp,data = f.28173),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28180),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28191),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28196),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28197),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28198),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28247),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28248),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28258),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.29652),col="gray")
  abline(lm(surv.time ~ test.temp,data = data_f),col="#4DAC26",lwd=3)
  
  #update axis
  axis(2, at=xs, labels=labs, cex.axis=1.2)
  par(mai=c(0.55,0.6,0,0.1))
  
  text(70,92,"Inbred lines",col="gray",adj=0,font=2,cex=1.2)
  text(70,85,"Pooled lines",adj=0,col="#4DAC26",font=2,cex=1.2)
  
  #-----------------------------------------------------------------------------
  #males
  # labels
  labs= c("1","2","5","10","30","120","420")
  xs= log10(c(1,2,5,10,30,60*2,60*7))
  
  par(mai=c(0.55,0.6,0,0.1))
  plot(surv.time ~ jitter(test.temp,0.5),xlim=c(35.6,39.4),ylim=c(0,3),yaxt="n",cex.axis=1.2, cex.lab=1.4,cex=1.4,pch=16,col="#A6761D70",xlab="Test temperature (°C)",ylab="Time (min)",data=m.25180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25182)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25190)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25192)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25201)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25203)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28135)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28141)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28153)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28173)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28191)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28196)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28197)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28247)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28248)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28258)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.29652)
  abline(lm(surv.time ~ test.temp,data = m.25180),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25182),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25190),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25192),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25198),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25201),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25203),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28135),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28141),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28153),col="gray")	
  abline(lm(surv.time ~ test.temp,data = m.28173),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28180),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28191),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28196),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28197),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28198),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28247),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28248),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28258),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.29652),col="gray")
  abline(lm(surv.time ~ test.temp,data = data_m),col="#A6761D",lwd=3)
  
  #update axis
  axis(2, at=xs, labels=labs, cex.axis=1.2)
  
  par(mai=c(0.55,0.6,0,0.1))
  
  text(70,0.92,"Inbred lines",col="gray",adj=0,font=2,cex=1.2)
  text(70,.85,"Pooled lines",adj=0,col="#A6761D",font=2,cex=1.2)
  
  # close device
  dev.off()
}

# Broad-sense heritability across females and females
p<-lm(value~Line,data=df.p20)
summary(p)
anova(p)
120505/(120505+343278) #genetic variation = 0.2598
#-------------------------------------------------------------------------------
#saving session information with all packages versions for reproducibility
#purposes
sink("../Outputs/1.1.1. Survival probability of DGRP lines_R_session.txt")
sessionInfo()
sink()
################################################################################
############################ END OF SCRIPT #####################################
################################################################################