# ------------------------------------------------------------------------------
# Script to calculate survival probabilities of DGRP lines under normoxia
# ------------------------------------------------------------------------------
# Data generated by Félix P Leiva (e-mail: felixpleiva@gmail.com)
# Script created by Félix P Leiva (e-mail: felixpleiva@gmail.com)
# ------------------------------------------------------------------------------
# Cite as:

# Leiva FP, Santos M, Rezende E, & Verberk WCEP. (2022). Data and code of
# manuscript: Genetic variation on heat tolerance in a model ectotherm. Zenodo.
# (DOI is coming)
# ------------------------------------------------------------------------------
# Cleaning working space
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# ------------------------------------------------------------------------------
# set the working directory to the folder containing this script:
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
# ------------------------------------------------------------------------------
# check directory
getwd()
# ------------------------------------------------------------------------------
#Libraries
library(lme4)
library(MuMIn)
# ------------------------------------------------------------------------------
# Download and read the function "Thermal landscape functions.R" from the paper
# "Predicting temperature mortality and selection in natural Drosophila
# populations" by Rezende et al 2020 Science 369, (6508) 1242-1245
# (10.1126/science.aba9287)
source("../Functions/Thermal landscape functions.R")
# ------------------------------------------------------------------------------
#Load data of the 20 DGRP lines
all.lines.21<-read.csv("../Outputs/0.1.1. Survival time of Drosophila melanogaster across DGRP lines.csv")

str(all.lines.21)
#stock as factor
all.lines.21$stock<-as.factor(all.lines.21$stock)
#-------------------------------------------------------------------------------
#transform minutes in log10-scale to minutes
all.lines.21$surv.time2<-as.numeric(10^(all.lines.21$surv.time))
#-------------------------------------------------------------------------------
# subset by sex
data_f<-subset(all.lines.21,sex=="female") #females
data_m<-subset(all.lines.21,sex=="male") #males
#-------------------------------------------------------------------------------
# subset by stock
levels(data_f$stock)
# [1] "25180" "25182" "25190" "25192" "25198" "25201" "25203" "28135" "28141" "28153"
# [11] "28173" "28180" "28191" "28196" "28197" "28198" "28247" "28248" "28258" "29652"
#-------------------------------------------------------------------------------
# SEXES POOLED
#-------------------------------------------------------------------------------
p.25180<-subset(all.lines.21,stock=="25180")
p1 <- tolerance.landscape(p.25180$test.temp,p.25180$surv.time2)
p1$Stime_resc<- 10^((1/p1$z)*(p1$ctmax-p1$ta.mn)+ #log time at median Ta
                      log10(p.25180$surv.time2)- #log time observed
                      (1/p1$z)*(p1$ctmax-p.25180$test.temp)) #log time expected
df.p1<-data.frame(Line=rep("p.25180",each=length(p1$Stime_resc)),
               value=p1$Stime_resc)

p.25182<-subset(all.lines.21,stock=="25182")
p2 <- tolerance.landscape(p.25182$test.temp,p.25182$surv.time2)
p2$Stime_resc<- 10^((1/p2$z)*(p2$ctmax-p2$ta.mn)+ #log time at median Ta
                      log10(p.25182$surv.time2)- #log time observed
                      (1/p2$z)*(p2$ctmax-p.25182$test.temp)) #log time expected
df.p2<-rbind(df.p1,data.frame(Line=rep("p.25182",each=length(p2$Stime_resc)),
                        value=p2$Stime_resc))

p.25190<-subset(all.lines.21,stock=="25190")
p3 <- tolerance.landscape(p.25190$test.temp,p.25190$surv.time2)
p3$Stime_resc<- 10^((1/p3$z)*(p3$ctmax-p3$ta.mn)+ #log time at median Ta
                      log10(p.25190$surv.time2)- #log time observed
                      (1/p3$z)*(p3$ctmax-p.25190$test.temp)) #log time expected
df.p3<-rbind(df.p2,data.frame(Line=rep("p.25190",each=length(p3$Stime_resc)),
                        value=p3$Stime_resc))

p.25192<-subset(all.lines.21,stock=="25192")
p4 <- tolerance.landscape(p.25192$test.temp,p.25192$surv.time2)
p4$Stime_resc<- 10^((1/p4$z)*(p4$ctmax-p4$ta.mn)+ #log time at median Ta
                      log10(p.25192$surv.time2)- #log time observed
                      (1/p4$z)*(p4$ctmax-p.25192$test.temp)) #log time expected
df.p4<-rbind(df.p3,data.frame(Line=rep("p.25192",each=length(p4$Stime_resc)),
                        value=p4$Stime_resc))

p.25198<-subset(all.lines.21,stock=="25198")
p5 <- tolerance.landscape(p.25198$test.temp,p.25198$surv.time2)
p5$Stime_resc<- 10^((1/p5$z)*(p5$ctmax-p5$ta.mn)+ #log time at median Ta
                      log10(p.25198$surv.time2)- #log time observed
                      (1/p5$z)*(p5$ctmax-p.25198$test.temp)) #log time expected
df.p5<-rbind(df.p4,data.frame(Line=rep("p.25198",each=length(p5$Stime_resc)),
                        value=p5$Stime_resc))

p.25201<-subset(all.lines.21,stock=="25201")
p6 <- tolerance.landscape(p.25201$test.temp,p.25201$surv.time2)
p6$Stime_resc<- 10^((1/p6$z)*(p6$ctmax-p6$ta.mn)+ #log time at median Ta
                      log10(p.25201$surv.time2)- #log time observed
                      (1/p6$z)*(p6$ctmax-p.25201$test.temp)) #log time expected
df.p6<-rbind(df.p5,data.frame(Line=rep("p.25201",each=length(p6$Stime_resc)),
                        value=p6$Stime_resc))

p.25203<-subset(all.lines.21,stock=="25203")
p7 <- tolerance.landscape(p.25203$test.temp,p.25203$surv.time2)
p7$Stime_resc<- 10^((1/p7$z)*(p7$ctmax-p7$ta.mn)+ #log time at median Ta
                      log10(p.25203$surv.time2)- #log time observed
                      (1/p7$z)*(p7$ctmax-p.25203$test.temp)) #log time expected
df.p7<-rbind(df.p6,data.frame(Line=rep("p.25203",each=length(p7$Stime_resc)),
                        value=p7$Stime_resc))

p.28135<-subset(all.lines.21,stock=="28135")
p8 <- tolerance.landscape(p.28135$test.temp,p.28135$surv.time2)
p8$Stime_resc<- 10^((1/p8$z)*(p8$ctmax-p8$ta.mn)+ #log time at median Ta
                      log10(p.28135$surv.time2)- #log time observed
                      (1/p8$z)*(p8$ctmax-p.28135$test.temp)) #log time expected
df.p8<-rbind(df.p7,data.frame(Line=rep("p.28135",each=length(p8$Stime_resc)),
                        value=p8$Stime_resc))

p.28141<-subset(all.lines.21,stock=="28141")
p9 <- tolerance.landscape(p.28141$test.temp,p.28141$surv.time2)
p9$Stime_resc<- 10^((1/p9$z)*(p9$ctmax-p9$ta.mn)+ #log time at median Ta
                      log10(p.28141$surv.time2)- #log time observed
                      (1/p9$z)*(p9$ctmax-p.28141$test.temp)) #log time expected
df.p9<-rbind(df.p8,data.frame(Line=rep("p.28141",each=length(p9$Stime_resc)),
                        value=p9$Stime_resc))

p.28153<-subset(all.lines.21,stock=="28153")
p10 <- tolerance.landscape(p.28153$test.temp,p.28153$surv.time2)
p10$Stime_resc<- 10^((1/p10$z)*(p10$ctmax-p10$ta.mn)+ #log time at median Ta
                       log10(p.28153$surv.time2)- #log time observed
                       (1/p10$z)*(p10$ctmax-p.28153$test.temp)) #log time expected
df.p10<-rbind(df.p9,data.frame(Line=rep("p.28153",each=length(p10$Stime_resc)),
                        value=p10$Stime_resc))

p.28173<-subset(all.lines.21,stock=="28173")
p11 <- tolerance.landscape(p.28173$test.temp,p.28173$surv.time2)
p11$Stime_resc<- 10^((1/p11$z)*(p11$ctmax-p5$ta.mn)+ #log time at median Ta
                       log10(p.28173$surv.time2)- #log time observed
                       (1/p11$z)*(p11$ctmax-p.28173$test.temp)) #log time expected
df.p11<-rbind(df.p10,data.frame(Line=rep("p.28173",each=length(p11$Stime_resc)),
                        value=p11$Stime_resc))

p.28180<-subset(all.lines.21,stock=="28180")
p12 <- tolerance.landscape(p.28180$test.temp,p.28180$surv.time2)
p12$Stime_resc<- 10^((1/p12$z)*(p12$ctmax-p12$ta.mn)+ #log time at median Ta
                       log10(p.28180$surv.time2)- #log time observed
                       (1/p12$z)*(p12$ctmax-p.28180$test.temp)) #log time expected
df.p12<-rbind(df.p11,data.frame(Line=rep("p.28180",each=length(p12$Stime_resc)),
                        value=p12$Stime_resc))

p.28191<-subset(all.lines.21,stock=="28191")
p13 <- tolerance.landscape(p.28191$test.temp,p.28191$surv.time2)
p13$Stime_resc<- 10^((1/p13$z)*(p13$ctmax-p13$ta.mn)+ #log time at median Ta
                       log10(p.28191$surv.time2)- #log time observed
                       (1/p13$z)*(p13$ctmax-p.28191$test.temp)) #log time expected
df.p13<-rbind(df.p12,data.frame(Line=rep("p.28191",each=length(p13$Stime_resc)),
                        value=p13$Stime_resc))

p.28196<-subset(all.lines.21,stock=="28196")
p14 <- tolerance.landscape(p.28196$test.temp,p.28196$surv.time2)
p14$Stime_resc<- 10^((1/p14$z)*(p14$ctmax-p14$ta.mn)+ #log time at median Ta
                       log10(p.28196$surv.time2)- #log time observed
                       (1/p14$z)*(p14$ctmax-p.28196$test.temp)) #log time expected
df.p14<-rbind(df.p13,data.frame(Line=rep("p.28196",each=length(p14$Stime_resc)),
                        value=p14$Stime_resc))

p.28197<-subset(all.lines.21,stock=="28197")
p15 <- tolerance.landscape(p.28197$test.temp,p.28197$surv.time2)
p15$Stime_resc<- 10^((1/p15$z)*(p15$ctmax-p15$ta.mn)+ #log time at median Ta
                       log10(p.28197$surv.time2)- #log time observed
                       (1/p15$z)*(p15$ctmax-p.28197$test.temp)) #log time expected
df.p15<-rbind(df.p14,data.frame(Line=rep("p.28197",each=length(p15$Stime_resc)),
                        value=p15$Stime_resc))

p.28198<-subset(all.lines.21,stock=="28198")
p16 <- tolerance.landscape(p.28198$test.temp,p.28198$surv.time2)
p16$Stime_resc<- 10^((1/p16$z)*(p16$ctmax-p16$ta.mn)+ #log time at median Ta
                       log10(p.28198$surv.time2)- #log time observed
                       (1/p16$z)*(p16$ctmax-p.28198$test.temp)) #log time expected
df.p16<-rbind(df.p15,data.frame(Line=rep("p.28198",each=length(p16$Stime_resc)),
                        value=p16$Stime_resc))

p.28247<-subset(all.lines.21,stock=="28247")
p17 <- tolerance.landscape(p.28247$test.temp,p.28247$surv.time2)
p17$Stime_resc<- 10^((1/p17$z)*(p17$ctmax-p17$ta.mn)+ #log time at median Ta
                       log10(p.28247$surv.time2)- #log time observed
                       (1/p17$z)*(p17$ctmax-p.28247$test.temp)) #log time expected
df.p17<-rbind(df.p16,data.frame(Line=rep("p.28247",each=length(p17$Stime_resc)),
                        value=p17$Stime_resc))

p.28248<-subset(all.lines.21,stock=="28248")
p18 <- tolerance.landscape(p.28248$test.temp,p.28248$surv.time2)
p18$Stime_resc<- 10^((1/p18$z)*(p18$ctmax-p18$ta.mn)+ #log time at median Ta
                       log10(p.28248$surv.time2)- #log time observed
                       (1/p18$z)*(p18$ctmax-p.28248$test.temp)) #log time expected
df.p18<-rbind(df.p17,data.frame(Line=rep("p.28248",each=length(p18$Stime_resc)),
                        value=p18$Stime_resc))

p.28258<-subset(all.lines.21,stock=="28258")
p19 <- tolerance.landscape(p.28258$test.temp,p.28258$surv.time2)
p19$Stime_resc<- 10^((1/p19$z)*(p19$ctmax-p19$ta.mn)+ #log time at median Ta
                       log10(p.28258$surv.time2)- #log time observed
                       (1/p19$z)*(p19$ctmax-p.28258$test.temp)) #log time expected
df.p19<-rbind(df.p18,data.frame(Line=rep("p.28258",each=length(p19$Stime_resc)),
                        value=p19$Stime_resc))

p.29652<-subset(all.lines.21,stock=="29652")
p20 <- tolerance.landscape(p.29652$test.temp,p.29652$surv.time2)
p20$Stime_resc<- 10^((1/p20$z)*(p20$ctmax-p20$ta.mn)+ #log time at median Ta
                       log10(p.29652$surv.time2)- #log time observed
                       (1/p20$z)*(p20$ctmax-p.29652$test.temp)) #log time expected
df.p20<-rbind(df.p19,data.frame(Line=rep("p.29652",each=length(p20$Stime_resc)),
                        value=p20$Stime_resc))

pall<-tolerance.landscape(all.lines.21$test.temp,all.lines.21$surv.time2)
pall$Stime_resc<- 10^((1/pall$z)*(pall$ctmax-pall$ta.mn)+ #log time at median Ta
                        log10(all.lines.21$surv.time2)- #log time observed
                        (1/pall$z)*(pall$ctmax-all.lines.21$test.temp)) #log time expected
#-------------------------------------------------------------------------------
# FEMALES
#-------------------------------------------------------------------------------
f.25180<-subset(data_f,stock=="25180")
f1 <- tolerance.landscape(f.25180$test.temp,f.25180$surv.time2)
f1$Stime_resc<- 10^((1/f1$z)*(f1$ctmax-f1$ta.mn)+ #log time at median Ta (in this case 37.5)
                      log10(f.25180$surv.time2)- #log time observed
                      (1/f1$z)*(f1$ctmax-f.25180$test.temp)) #log time expected
df.f1<-data.frame(Line=rep("f.25180",each=length(f1$Stime_resc)),
                  value=f1$Stime_resc)

f.25182<-subset(data_f,stock=="25182")
f2 <- tolerance.landscape(f.25182$test.temp,f.25182$surv.time2)
f2$Stime_resc<- 10^((1/f2$z)*(f2$ctmax-f2$ta.mn)+ #log time at median Ta
                      log10(f.25182$surv.time2)- #log time observed
                      (1/f2$z)*(f2$ctmax-f.25182$test.temp)) #log time expected
df.f2<-rbind(df.f1,data.frame(Line=rep("f.25182",each=length(f2$Stime_resc)),
                              value=f2$Stime_resc))

f.25190<-subset(data_f,stock=="25190")
f3 <- tolerance.landscape(f.25190$test.temp,f.25190$surv.time2)
f3$Stime_resc<- 10^((1/f3$z)*(f3$ctmax-f3$ta.mn)+ #log time at median Ta
                      log10(f.25190$surv.time2)- #log time observed
                      (1/f3$z)*(f3$ctmax-f.25190$test.temp)) #log time expected
df.f3<-rbind(df.f2,data.frame(Line=rep("f.25190",each=length(f3$Stime_resc)),
                              value=f3$Stime_resc))

f.25192<-subset(data_f,stock=="25192")
f4 <- tolerance.landscape(f.25192$test.temp,f.25192$surv.time2)
f4$Stime_resc<- 10^((1/f4$z)*(f4$ctmax-f4$ta.mn)+ #log time at median Ta
                      log10(f.25192$surv.time2)- #log time observed
                      (1/f4$z)*(f4$ctmax-f.25192$test.temp)) #log time expected
df.f4<-rbind(df.f3,data.frame(Line=rep("f.25192",each=length(f4$Stime_resc)),
                              value=f4$Stime_resc))

f.25198<-subset(data_f,stock=="25198")
f5 <- tolerance.landscape(f.25198$test.temp,f.25198$surv.time2)
f5$Stime_resc<- 10^((1/f5$z)*(f5$ctmax-f5$ta.mn)+ #log time at median Ta
                      log10(f.25198$surv.time2)- #log time observed
                      (1/f5$z)*(f5$ctmax-f.25198$test.temp)) #log time expected
df.f5<-rbind(df.f4,data.frame(Line=rep("f.25198",each=length(f5$Stime_resc)),
                              value=f5$Stime_resc))

f.25201<-subset(data_f,stock=="25201")
f6 <- tolerance.landscape(f.25201$test.temp,f.25201$surv.time2)
f6$Stime_resc<- 10^((1/f6$z)*(f6$ctmax-f6$ta.mn)+ #log time at median Ta
                      log10(f.25201$surv.time2)- #log time observed
                      (1/f6$z)*(f6$ctmax-f.25201$test.temp)) #log time expected
df.f6<-rbind(df.f5,data.frame(Line=rep("f.25201",each=length(f6$Stime_resc)),
                              value=f6$Stime_resc))

f.25203<-subset(data_f,stock=="25203")
f7 <- tolerance.landscape(f.25203$test.temp,f.25203$surv.time2)
f7$Stime_resc<- 10^((1/f7$z)*(f7$ctmax-f7$ta.mn)+ #log time at median Ta
                      log10(f.25203$surv.time2)- #log time observed
                      (1/f7$z)*(f7$ctmax-f.25203$test.temp)) #log time expected
df.f7<-rbind(df.f6,data.frame(Line=rep("f.25203",each=length(f7$Stime_resc)),
                              value=f7$Stime_resc))

f.28135<-subset(data_f,stock=="28135")
f8 <- tolerance.landscape(f.28135$test.temp,f.28135$surv.time2)
f8$Stime_resc<- 10^((1/f8$z)*(f8$ctmax-f8$ta.mn)+ #log time at median Ta
                      log10(f.28135$surv.time2)- #log time observed
                      (1/f8$z)*(f8$ctmax-f.28135$test.temp)) #log time expected
df.f8<-rbind(df.f7,data.frame(Line=rep("f.28135",each=length(f8$Stime_resc)),
                              value=f8$Stime_resc))

f.28141<-subset(data_f,stock=="28141")
f9 <- tolerance.landscape(f.28141$test.temp,f.28141$surv.time2)
f9$Stime_resc<- 10^((1/f9$z)*(f9$ctmax-f9$ta.mn)+ #log time at median Ta
                      log10(f.28141$surv.time2)- #log time observed
                      (1/f9$z)*(f9$ctmax-f.28141$test.temp)) #log time expected
df.f9<-rbind(df.f8,data.frame(Line=rep("f.28141",each=length(f9$Stime_resc)),
                              value=f9$Stime_resc))

f.28153<-subset(data_f,stock=="28153")
f10 <- tolerance.landscape(f.28153$test.temp,f.28153$surv.time2)
f10$Stime_resc<- 10^((1/f10$z)*(f10$ctmax-f10$ta.mn)+ #log time at median Ta
                       log10(f.28153$surv.time2)- #log time observed
                       (1/f10$z)*(f10$ctmax-f.28153$test.temp)) #log time expected
df.f10<-rbind(df.f9,data.frame(Line=rep("f.28153",each=length(f10$Stime_resc)),
                               value=f10$Stime_resc))

f.28173<-subset(data_f,stock=="28173")
f11 <- tolerance.landscape(f.28173$test.temp,f.28173$surv.time2)
f11$Stime_resc<- 10^((1/f11$z)*(f11$ctmax-p5$ta.mn)+ #log time at median Ta
                       log10(f.28173$surv.time2)- #log time observed
                       (1/f11$z)*(f11$ctmax-f.28173$test.temp)) #log time expected
df.f11<-rbind(df.f10,data.frame(Line=rep("f.28173",each=length(f11$Stime_resc)),
                                value=f11$Stime_resc))

f.28180<-subset(data_f,stock=="28180")
f12 <- tolerance.landscape(f.28180$test.temp,f.28180$surv.time2)
f12$Stime_resc<- 10^((1/f12$z)*(f12$ctmax-f12$ta.mn)+ #log time at median Ta
                       log10(f.28180$surv.time2)- #log time observed
                       (1/f12$z)*(f12$ctmax-f.28180$test.temp)) #log time expected
df.f12<-rbind(df.f11,data.frame(Line=rep("f.28180",each=length(f12$Stime_resc)),
                                value=f12$Stime_resc))

f.28191<-subset(data_f,stock=="28191")
f13 <- tolerance.landscape(f.28191$test.temp,f.28191$surv.time2)
f13$Stime_resc<- 10^((1/f13$z)*(f13$ctmax-f13$ta.mn)+ #log time at median Ta
                       log10(f.28191$surv.time2)- #log time observed
                       (1/f13$z)*(f13$ctmax-f.28191$test.temp)) #log time expected
df.f13<-rbind(df.f12,data.frame(Line=rep("f.28191",each=length(f13$Stime_resc)),
                                value=f13$Stime_resc))

f.28196<-subset(data_f,stock=="28196")
f14 <- tolerance.landscape(f.28196$test.temp,f.28196$surv.time2)
f14$Stime_resc<- 10^((1/f14$z)*(f14$ctmax-f14$ta.mn)+ #log time at median Ta
                       log10(f.28196$surv.time2)- #log time observed
                       (1/f14$z)*(f14$ctmax-f.28196$test.temp)) #log time expected
df.f14<-rbind(df.f13,data.frame(Line=rep("f.28196",each=length(f14$Stime_resc)),
                                value=f14$Stime_resc))

f.28197<-subset(data_f,stock=="28197")
f15 <- tolerance.landscape(f.28197$test.temp,f.28197$surv.time2)
f15$Stime_resc<- 10^((1/f15$z)*(f15$ctmax-f15$ta.mn)+ #log time at median Ta
                       log10(f.28197$surv.time2)- #log time observed
                       (1/f15$z)*(f15$ctmax-f.28197$test.temp)) #log time expected
df.f15<-rbind(df.f14,data.frame(Line=rep("f.28197",each=length(f15$Stime_resc)),
                                value=f15$Stime_resc))

f.28198<-subset(data_f,stock=="28198")
f16 <- tolerance.landscape(f.28198$test.temp,f.28198$surv.time2)
f16$Stime_resc<- 10^((1/f16$z)*(f16$ctmax-f16$ta.mn)+ #log time at median Ta
                       log10(f.28198$surv.time2)- #log time observed
                       (1/f16$z)*(f16$ctmax-f.28198$test.temp)) #log time expected
df.f16<-rbind(df.f15,data.frame(Line=rep("f.28198",each=length(f16$Stime_resc)),
                                value=f16$Stime_resc))

f.28247<-subset(data_f,stock=="28247")
f17 <- tolerance.landscape(f.28247$test.temp,f.28247$surv.time2)
f17$Stime_resc<- 10^((1/f17$z)*(f17$ctmax-f17$ta.mn)+ #log time at median Ta
                       log10(f.28247$surv.time2)- #log time observed
                       (1/f17$z)*(f17$ctmax-f.28247$test.temp)) #log time expected
df.f17<-rbind(df.f16,data.frame(Line=rep("f.28247",each=length(f17$Stime_resc)),
                                value=f17$Stime_resc))

f.28248<-subset(data_f,stock=="28248")
f18 <- tolerance.landscape(f.28248$test.temp,f.28248$surv.time2)
f18$Stime_resc<- 10^((1/f18$z)*(f18$ctmax-f18$ta.mn)+ #log time at median Ta
                       log10(f.28248$surv.time2)- #log time observed
                       (1/f18$z)*(f18$ctmax-f.28248$test.temp)) #log time expected
df.f18<-rbind(df.f17,data.frame(Line=rep("f.28248",each=length(f18$Stime_resc)),
                                value=f18$Stime_resc))

f.28258<-subset(data_f,stock=="28258")
f19 <- tolerance.landscape(f.28258$test.temp,f.28258$surv.time2)
f19$Stime_resc<- 10^((1/f19$z)*(f19$ctmax-f19$ta.mn)+ #log time at median Ta
                       log10(f.28258$surv.time2)- #log time observed
                       (1/f19$z)*(f19$ctmax-f.28258$test.temp)) #log time expected
df.f19<-rbind(df.f18,data.frame(Line=rep("f.28258",each=length(f19$Stime_resc)),
                                value=f19$Stime_resc))

f.29652<-subset(data_f,stock=="29652")
f20 <- tolerance.landscape(f.29652$test.temp,f.29652$surv.time2)
f20$Stime_resc<- 10^((1/f20$z)*(f20$ctmax-f20$ta.mn)+ #log time at median Ta
                       log10(f.29652$surv.time2)- #log time observed
                       (1/f20$z)*(f20$ctmax-f.29652$test.temp)) #log time expected
df.f20<-rbind(df.f19,data.frame(Line=rep("f.29652",each=length(f20$Stime_resc)),
                                value=f20$Stime_resc))

fall<-tolerance.landscape(data_f$test.temp,data_f$surv.time2)
fall$Stime_resc<- 10^((1/fall$z)*(fall$ctmax-fall$ta.mn)+ #log time at median Ta
                        log10(data_f$surv.time2)- #log time observed
                        (1/fall$z)*(fall$ctmax-data_f$test.temp)) #log time expected
#-------------------------------------------------------------------------------
# MALES
#-------------------------------------------------------------------------------
m.25180<-subset(data_m,stock=="25180")
m1 <- tolerance.landscape(m.25180$test.temp,m.25180$surv.time2)
m1$Stime_resc<- 10^((1/m1$z)*(m1$ctmax-m1$ta.mn)+ #log time at median Ta
                      log10(m.25180$surv.time2)- #log time observed
                      (1/m1$z)*(m1$ctmax-m.25180$test.temp)) #log time expected
df.m1<-data.frame(Line=rep("m.25180",each=length(m1$Stime_resc)),
                  value=m1$Stime_resc)

m.25182<-subset(data_m,stock=="25182")
m2 <- tolerance.landscape(m.25182$test.temp,m.25182$surv.time2)
m2$Stime_resc<- 10^((1/m2$z)*(m2$ctmax-m2$ta.mn)+ #log time at median Ta
                      log10(m.25182$surv.time2)- #log time observed
                      (1/m2$z)*(m2$ctmax-m.25182$test.temp)) #log time expected
df.m2<-rbind(df.m1,data.frame(Line=rep("m.25182",each=length(m2$Stime_resc)),
                              value=m2$Stime_resc))

m.25190<-subset(data_m,stock=="25190")
m3 <- tolerance.landscape(m.25190$test.temp,m.25190$surv.time2)
m3$Stime_resc<- 10^((1/m3$z)*(m3$ctmax-m3$ta.mn)+ #log time at median Ta
                      log10(m.25190$surv.time2)- #log time observed
                      (1/m3$z)*(m3$ctmax-m.25190$test.temp)) #log time expected
df.m3<-rbind(df.m2,data.frame(Line=rep("m.25190",each=length(m3$Stime_resc)),
                              value=m3$Stime_resc))

m.25192<-subset(data_m,stock=="25192")
m4 <- tolerance.landscape(m.25192$test.temp,m.25192$surv.time2)
m4$Stime_resc<- 10^((1/m4$z)*(m4$ctmax-m4$ta.mn)+ #log time at median Ta
                      log10(m.25192$surv.time2)- #log time observed
                      (1/m4$z)*(m4$ctmax-m.25192$test.temp)) #log time expected
df.m4<-rbind(df.m3,data.frame(Line=rep("m.25192",each=length(m4$Stime_resc)),
                              value=m4$Stime_resc))

m.25198<-subset(data_m,stock=="25198")
m5 <- tolerance.landscape(m.25198$test.temp,m.25198$surv.time2)
m5$Stime_resc<- 10^((1/m5$z)*(m5$ctmax-m5$ta.mn)+ #log time at median Ta
                      log10(m.25198$surv.time2)- #log time observed
                      (1/m5$z)*(m5$ctmax-m.25198$test.temp)) #log time expected
df.m5<-rbind(df.m4,data.frame(Line=rep("m.25198",each=length(m5$Stime_resc)),
                              value=m5$Stime_resc))

m.25201<-subset(data_m,stock=="25201")
m6 <- tolerance.landscape(m.25201$test.temp,m.25201$surv.time2)
m6$Stime_resc<- 10^((1/m6$z)*(m6$ctmax-m6$ta.mn)+ #log time at median Ta
                      log10(m.25201$surv.time2)- #log time observed
                      (1/m6$z)*(m6$ctmax-m.25201$test.temp)) #log time expected
df.m6<-rbind(df.m5,data.frame(Line=rep("m.25201",each=length(m6$Stime_resc)),
                              value=m6$Stime_resc))

m.25203<-subset(data_m,stock=="25203")
m7 <- tolerance.landscape(m.25203$test.temp,m.25203$surv.time2)
m7$Stime_resc<- 10^((1/m7$z)*(m7$ctmax-m7$ta.mn)+ #log time at median Ta
                      log10(m.25203$surv.time2)- #log time observed
                      (1/m7$z)*(m7$ctmax-m.25203$test.temp)) #log time expected
df.m7<-rbind(df.m6,data.frame(Line=rep("m.25203",each=length(m7$Stime_resc)),
                              value=m7$Stime_resc))

m.28135<-subset(data_m,stock=="28135")
m8 <- tolerance.landscape(m.28135$test.temp,m.28135$surv.time2)
m8$Stime_resc<- 10^((1/m8$z)*(m8$ctmax-m8$ta.mn)+ #log time at median Ta
                      log10(m.28135$surv.time2)- #log time observed
                      (1/m8$z)*(m8$ctmax-m.28135$test.temp)) #log time expected
df.m8<-rbind(df.m7,data.frame(Line=rep("m.28135",each=length(m8$Stime_resc)),
                              value=m8$Stime_resc))

m.28141<-subset(data_m,stock=="28141")
m9 <- tolerance.landscape(m.28141$test.temp,m.28141$surv.time2)
m9$Stime_resc<- 10^((1/m9$z)*(m9$ctmax-m9$ta.mn)+ #log time at median Ta
                      log10(m.28141$surv.time2)- #log time observed
                      (1/m9$z)*(m9$ctmax-m.28141$test.temp)) #log time expected
df.m9<-rbind(df.m8,data.frame(Line=rep("m.28141",each=length(m9$Stime_resc)),
                              value=m9$Stime_resc))

m.28153<-subset(data_m,stock=="28153")
m10 <- tolerance.landscape(m.28153$test.temp,m.28153$surv.time2)
m10$Stime_resc<- 10^((1/m10$z)*(m10$ctmax-m10$ta.mn)+ #log time at median Ta
                       log10(m.28153$surv.time2)- #log time observed
                       (1/m10$z)*(m10$ctmax-m.28153$test.temp)) #log time expected
df.m10<-rbind(df.m9,data.frame(Line=rep("m.28153",each=length(m10$Stime_resc)),
                               value=m10$Stime_resc))

m.28173<-subset(data_m,stock=="28173")
m11 <- tolerance.landscape(m.28173$test.temp,m.28173$surv.time2)
m11$Stime_resc<- 10^((1/m11$z)*(m11$ctmax-p5$ta.mn)+ #log time at median Ta
                       log10(m.28173$surv.time2)- #log time observed
                       (1/m11$z)*(m11$ctmax-m.28173$test.temp)) #log time expected
df.m11<-rbind(df.m10,data.frame(Line=rep("m.28173",each=length(m11$Stime_resc)),
                                value=m11$Stime_resc))

m.28180<-subset(data_m,stock=="28180")
m12 <- tolerance.landscape(m.28180$test.temp,m.28180$surv.time2)
m12$Stime_resc<- 10^((1/m12$z)*(m12$ctmax-m12$ta.mn)+ #log time at median Ta
                       log10(m.28180$surv.time2)- #log time observed
                       (1/m12$z)*(m12$ctmax-m.28180$test.temp)) #log time expected
df.m12<-rbind(df.m11,data.frame(Line=rep("m.28180",each=length(m12$Stime_resc)),
                                value=m12$Stime_resc))

m.28191<-subset(data_m,stock=="28191")
m13 <- tolerance.landscape(m.28191$test.temp,m.28191$surv.time2)
m13$Stime_resc<- 10^((1/m13$z)*(m13$ctmax-m13$ta.mn)+ #log time at median Ta
                       log10(m.28191$surv.time2)- #log time observed
                       (1/m13$z)*(m13$ctmax-m.28191$test.temp)) #log time expected
df.m13<-rbind(df.m12,data.frame(Line=rep("m.28191",each=length(m13$Stime_resc)),
                                value=m13$Stime_resc))

m.28196<-subset(data_m,stock=="28196")
m14 <- tolerance.landscape(m.28196$test.temp,m.28196$surv.time2)
m14$Stime_resc<- 10^((1/m14$z)*(m14$ctmax-m14$ta.mn)+ #log time at median Ta
                       log10(m.28196$surv.time2)- #log time observed
                       (1/m14$z)*(m14$ctmax-m.28196$test.temp)) #log time expected
df.m14<-rbind(df.m13,data.frame(Line=rep("m.28196",each=length(m14$Stime_resc)),
                                value=m14$Stime_resc))

m.28197<-subset(data_m,stock=="28197")
m15 <- tolerance.landscape(m.28197$test.temp,m.28197$surv.time2)
m15$Stime_resc<- 10^((1/m15$z)*(m15$ctmax-m15$ta.mn)+ #log time at median Ta
                       log10(m.28197$surv.time2)- #log time observed
                       (1/m15$z)*(m15$ctmax-m.28197$test.temp)) #log time expected
df.m15<-rbind(df.m14,data.frame(Line=rep("m.28197",each=length(m15$Stime_resc)),
                                value=m15$Stime_resc))

m.28198<-subset(data_m,stock=="28198")
m16 <- tolerance.landscape(m.28198$test.temp,m.28198$surv.time2)
m16$Stime_resc<- 10^((1/m16$z)*(m16$ctmax-m16$ta.mn)+ #log time at median Ta
                       log10(m.28198$surv.time2)- #log time observed
                       (1/m16$z)*(m16$ctmax-m.28198$test.temp)) #log time expected
df.m16<-rbind(df.m15,data.frame(Line=rep("m.28198",each=length(m16$Stime_resc)),
                                value=m16$Stime_resc))

m.28247<-subset(data_m,stock=="28247")
m17 <- tolerance.landscape(m.28247$test.temp,m.28247$surv.time2)
m17$Stime_resc<- 10^((1/m17$z)*(m17$ctmax-m17$ta.mn)+ #log time at median Ta
                       log10(m.28247$surv.time2)- #log time observed
                       (1/m17$z)*(m17$ctmax-m.28247$test.temp)) #log time expected
df.m17<-rbind(df.m16,data.frame(Line=rep("m.28247",each=length(m17$Stime_resc)),
                                value=m17$Stime_resc))

m.28248<-subset(data_m,stock=="28248")
m18 <- tolerance.landscape(m.28248$test.temp,m.28248$surv.time2)
m18$Stime_resc<- 10^((1/m18$z)*(m18$ctmax-m18$ta.mn)+ #log time at median Ta
                       log10(m.28248$surv.time2)- #log time observed
                       (1/m18$z)*(m18$ctmax-m.28248$test.temp)) #log time expected
df.m18<-rbind(df.m17,data.frame(Line=rep("m.28248",each=length(m18$Stime_resc)),
                                value=m18$Stime_resc))

m.28258<-subset(data_m,stock=="28258")
m19 <- tolerance.landscape(m.28258$test.temp,m.28258$surv.time2)
m19$Stime_resc<- 10^((1/m19$z)*(m19$ctmax-m19$ta.mn)+ #log time at median Ta
                       log10(m.28258$surv.time2)- #log time observed
                       (1/m19$z)*(m19$ctmax-m.28258$test.temp)) #log time expected
df.m19<-rbind(df.m18,data.frame(Line=rep("m.28258",each=length(m19$Stime_resc)),
                                value=m19$Stime_resc))

m.29652<-subset(data_m,stock=="29652")
m20 <- tolerance.landscape(m.29652$test.temp,m.29652$surv.time2)
m20$Stime_resc<- 10^((1/m20$z)*(m20$ctmax-m20$ta.mn)+ #log time at median Ta
                       log10(m.29652$surv.time2)- #log time observed
                       (1/m20$z)*(m20$ctmax-m.29652$test.temp)) #log time expected
df.m20<-rbind(df.m19,data.frame(Line=rep("m.29652",each=length(m20$Stime_resc)),
                                value=m20$Stime_resc))

mall<-tolerance.landscape(data_m$test.temp,data_m$surv.time2)
mall$Stime_resc<- 10^((1/pall$z)*(pall$ctmax-pall$ta.mn)+ #log time at median Ta
                        log10(data_m$surv.time2)- #log time observed
                        (1/pall$z)*(pall$ctmax-data_m$test.temp)) #log time expected
#-------------------------------------------------------------------------------
# FIGURE 1
#-------------------------------------------------------------------------------
{
  #pdf("../Outputs/1.2.1. Figure 1 Survival probabilities of DGRP lines.pdf",width = 6,height = 8,useDingbats = FALSE)
  png("../Outputs/1.2.1. Figure 1 Survival probabilities of DGRP lines.png",width = 6,height = 8,units = "in",res = 600)
  par(mfrow=c(3,2),tcl=-0.4, family="serif",omi=c(0,0,0,0))
  
  #Sexes pooled
  # labels
  labs= c("1","2","5","10","30","120","420")
  xs= log10(c(1,2,5,10,30,60*2,60*7))
  
  par(mai=c(0.55,0.6,0.1,0.1))
  #TDT plots
  plot(surv.time ~ jitter(test.temp,0.5),xlim=c(35.6,39.4),ylim=c(0,3),cex.axis=1.2, 
       cex.lab=1.4,yaxt="n",cex=1.4,pch=16,col="#55555540",xlab="",ylab="",data=p.25180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25182)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25190)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25192)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25201)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.25203)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28135)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28141)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28153)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28173)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28191)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28196)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28197)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28247)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28248)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.28258)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#55555540",data=p.29652)
  abline(lm(surv.time ~ test.temp,data = p.25180),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25182),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25190),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25192),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25198),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25201),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.25203),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28135),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28141),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28153),col="gray")	
  abline(lm(surv.time ~ test.temp,data = p.28173),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28180),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28191),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28196),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28197),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28198),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28247),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28248),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.28258),col="gray")
  abline(lm(surv.time ~ test.temp,data = p.29652),col="gray")
  abline(lm(surv.time ~ test.temp,data = all.lines.21),col="#555555",lwd=3)
  
  #update axis
  axis(2, at=xs, labels=labs, cex.axis=1.2)
  
  #survival plots
  par(mai=c(0.55,0.6,0.1,0.1))
  plot(sort(p1$Stime_resc),rev(100*(1:length(p1$Stime_resc)-1)/(length(p1$Stime_resc)-1)),
     col="gray",type="l",ylab="Survival probability",xlab="",cex.axis=1.2, cex.lab=1.4,las=1,xlim=c(0,110))
  points(sort(p2$Stime_resc),rev(100*(1:length(p2$Stime_resc)-1)/(length(p2$Stime_resc)-1)),col="gray",type="l")
  points(sort(p3$Stime_resc),rev(100*(1:length(p3$Stime_resc)-1)/(length(p3$Stime_resc)-1)),col="gray",type="l")
  points(sort(p4$Stime_resc),rev(100*(1:length(p4$Stime_resc)-1)/(length(p4$Stime_resc)-1)),col="gray",type="l")
  points(sort(p5$Stime_resc),rev(100*(1:length(p5$Stime_resc)-1)/(length(p5$Stime_resc)-1)),col="gray",type="l")
  points(sort(p6$Stime_resc),rev(100*(1:length(p6$Stime_resc)-1)/(length(p6$Stime_resc)-1)),col="gray",type="l")
  points(sort(p7$Stime_resc),rev(100*(1:length(p7$Stime_resc)-1)/(length(p7$Stime_resc)-1)),col="gray",type="l")
  points(sort(p8$Stime_resc),rev(100*(1:length(p8$Stime_resc)-1)/(length(p8$Stime_resc)-1)),col="gray",type="l")
  points(sort(p9$Stime_resc),rev(100*(1:length(p9$Stime_resc)-1)/(length(p9$Stime_resc)-1)),col="gray",type="l")
  points(sort(p10$Stime_resc),rev(100*(1:length(p10$Stime_resc)-1)/(length(p10$Stime_resc)-1)),col="gray",type="l")
  points(sort(p11$Stime_resc),rev(100*(1:length(p11$Stime_resc)-1)/(length(p11$Stime_resc)-1)),col="gray",type="l")
  points(sort(p12$Stime_resc),rev(100*(1:length(p12$Stime_resc)-1)/(length(p12$Stime_resc)-1)),col="gray",type="l")
  points(sort(p13$Stime_resc),rev(100*(1:length(p13$Stime_resc)-1)/(length(p13$Stime_resc)-1)),col="gray",type="l")
  points(sort(p14$Stime_resc),rev(100*(1:length(p14$Stime_resc)-1)/(length(p14$Stime_resc)-1)),col="gray",type="l")
  points(sort(p15$Stime_resc),rev(100*(1:length(p15$Stime_resc)-1)/(length(p15$Stime_resc)-1)),col="gray",type="l")
  points(sort(p16$Stime_resc),rev(100*(1:length(p16$Stime_resc)-1)/(length(p16$Stime_resc)-1)),col="gray",type="l")
  points(sort(p17$Stime_resc),rev(100*(1:length(p17$Stime_resc)-1)/(length(p17$Stime_resc)-1)),col="gray",type="l")
  points(sort(p18$Stime_resc),rev(100*(1:length(p18$Stime_resc)-1)/(length(p18$Stime_resc)-1)),col="gray",type="l")
  points(sort(p19$Stime_resc),rev(100*(1:length(p19$Stime_resc)-1)/(length(p19$Stime_resc)-1)),col="gray",type="l")
  points(sort(p20$Stime_resc),rev(100*(1:length(p20$Stime_resc)-1)/(length(p20$Stime_resc)-1)),col="gray",type="l")
  points(sort(pall$Stime_resc),rev(100*(1:length(pall$Stime_resc)-1)/(length(pall$Stime_resc)-1)),col="#555555",lwd=3,type="l")
  text(70,92,"Inbred lines",col="gray",adj=0,font=2,cex=1.2)
  text(70,85,"Pooled lines",adj=0,col="#555555",font=2,cex=1.2)
  
  #-----------------------------------------------------------------------------
  #females
  # labels
  labs= c("1","2","5","10","30","120","420")
  xs= log10(c(1,2,5,10,30,60*2,60*7))
  #TDT curves
  par(mai=c(0.55,0.6,0,0.1))
  plot(surv.time ~ jitter(test.temp,0.5),xlim=c(35.6,39.4),ylim=c(0,3),cex.axis=1.2, cex.lab=1.4,yaxt="n",cex=1.4,pch=16,
       col="#4DAC2660",xlab="",ylab="",data=f.25180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25182)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25190)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25192)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25201)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25203)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28135)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28141)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28153)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28173)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28191)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28196)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28197)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28247)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28248)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28258)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.29652)
  abline(lm(surv.time ~ test.temp,data = f.25180),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25182),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25190),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25192),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25198),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25201),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.25203),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28135),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28141),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28153),col="gray")	
  abline(lm(surv.time ~ test.temp,data = f.28173),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28180),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28191),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28196),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28197),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28198),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28247),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28248),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.28258),col="gray")
  abline(lm(surv.time ~ test.temp,data = f.29652),col="gray")
  abline(lm(surv.time ~ test.temp,data = data_f),col="#4DAC26",lwd=3)
  
  #update axis
  axis(2, at=xs, labels=labs, cex.axis=1.2)
  par(mai=c(0.55,0.6,0,0.1))
  plot(sort(f1$Stime_resc),rev(100*(1:length(f1$Stime_resc)-1)/(length(f1$Stime_resc)-1)),
       col="gray",type="l",ylab="Survival probability",cex.axis=1.2,xlab="",cex.lab=1.4,las=1,xlim=c(0,110))
  points(sort(f2$Stime_resc),rev(100*(1:length(f2$Stime_resc)-1)/(length(f2$Stime_resc)-1)),col="gray",type="l")
  points(sort(f3$Stime_resc),rev(100*(1:length(f3$Stime_resc)-1)/(length(f3$Stime_resc)-1)),col="gray",type="l")
  points(sort(f4$Stime_resc),rev(100*(1:length(f4$Stime_resc)-1)/(length(f4$Stime_resc)-1)),col="gray",type="l")
  points(sort(f5$Stime_resc),rev(100*(1:length(f5$Stime_resc)-1)/(length(f5$Stime_resc)-1)),col="gray",type="l")
  points(sort(f6$Stime_resc),rev(100*(1:length(f6$Stime_resc)-1)/(length(f6$Stime_resc)-1)),col="gray",type="l")
  points(sort(f7$Stime_resc),rev(100*(1:length(f7$Stime_resc)-1)/(length(f7$Stime_resc)-1)),col="gray",type="l")
  points(sort(f8$Stime_resc),rev(100*(1:length(f8$Stime_resc)-1)/(length(f8$Stime_resc)-1)),col="gray",type="l")
  points(sort(f9$Stime_resc),rev(100*(1:length(f9$Stime_resc)-1)/(length(f9$Stime_resc)-1)),col="gray",type="l")
  points(sort(f10$Stime_resc),rev(100*(1:length(f10$Stime_resc)-1)/(length(f10$Stime_resc)-1)),col="gray",type="l")
  points(sort(f11$Stime_resc),rev(100*(1:length(f11$Stime_resc)-1)/(length(f11$Stime_resc)-1)),col="gray",type="l")
  points(sort(f12$Stime_resc),rev(100*(1:length(f12$Stime_resc)-1)/(length(f12$Stime_resc)-1)),col="gray",type="l")
  points(sort(f13$Stime_resc),rev(100*(1:length(f13$Stime_resc)-1)/(length(f13$Stime_resc)-1)),col="gray",type="l")
  points(sort(f14$Stime_resc),rev(100*(1:length(f14$Stime_resc)-1)/(length(f14$Stime_resc)-1)),col="gray",type="l")
  points(sort(f15$Stime_resc),rev(100*(1:length(f15$Stime_resc)-1)/(length(f15$Stime_resc)-1)),col="gray",type="l")
  points(sort(f16$Stime_resc),rev(100*(1:length(f16$Stime_resc)-1)/(length(f16$Stime_resc)-1)),col="gray",type="l")
  points(sort(f17$Stime_resc),rev(100*(1:length(f17$Stime_resc)-1)/(length(f17$Stime_resc)-1)),col="gray",type="l")
  points(sort(f18$Stime_resc),rev(100*(1:length(f18$Stime_resc)-1)/(length(f18$Stime_resc)-1)),col="gray",type="l")
  points(sort(f19$Stime_resc),rev(100*(1:length(f19$Stime_resc)-1)/(length(f19$Stime_resc)-1)),col="gray",type="l")
  points(sort(f20$Stime_resc),rev(100*(1:length(f20$Stime_resc)-1)/(length(f20$Stime_resc)-1)),col="gray",type="l")
  points(sort(fall$Stime_resc),rev(100*(1:length(fall$Stime_resc)-1)/(length(fall$Stime_resc)-1)),col="#4DAC26",lwd=3,type="l")
  text(70,92,"Inbred lines",col="gray",adj=0,font=2,cex=1.2)
  text(70,85,"Pooled lines",adj=0,col="#4DAC26",font=2,cex=1.2)
  #-----------------------------------------------------------------------------
  #males
  # labels
  labs= c("1","2","5","10","30","120","420")
  xs= log10(c(1,2,5,10,30,60*2,60*7))
  
  par(mai=c(0.55,0.6,0,0.1))
  plot(surv.time ~ jitter(test.temp,0.5),xlim=c(35.6,39.4),ylim=c(0,3),yaxt="n",
       cex.axis=1.2, cex.lab=1.4,cex=1.4,pch=16,col="#A6761D70",
       xlab="Test temperature (°C)",ylab="Time (min)",data=m.25180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25182)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25190)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25192)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25201)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25203)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28135)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28141)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28153)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28173)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28180)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28191)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28196)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28197)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28198)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28247)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28248)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28258)
  points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.29652)
  abline(lm(surv.time ~ test.temp,data = m.25180),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25182),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25190),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25192),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25198),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25201),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.25203),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28135),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28141),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28153),col="gray")	
  abline(lm(surv.time ~ test.temp,data = m.28173),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28180),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28191),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28196),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28197),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28198),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28247),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28248),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.28258),col="gray")
  abline(lm(surv.time ~ test.temp,data = m.29652),col="gray")
  abline(lm(surv.time ~ test.temp,data = data_m),col="#A6761D",lwd=3)
  
  #update axis
  axis(2, at=xs, labels=labs, cex.axis=1.2)
  
  par(mai=c(0.55,0.6,0,0.1))
  plot(sort(m1$Stime_resc),rev(100*(1:length(m1$Stime_resc)-1)/(length(m1$Stime_resc)-1)),
       col="gray",type="l",ylab="Survival probability",xlab="Time (min)",cex.axis=1.2, cex.lab=1.4,las=1,xlim=c(0,110))
  points(sort(m2$Stime_resc),rev(100*(1:length(m2$Stime_resc)-1)/(length(m2$Stime_resc)-1)),col="gray",type="l")
  points(sort(m3$Stime_resc),rev(100*(1:length(m3$Stime_resc)-1)/(length(m3$Stime_resc)-1)),col="gray",type="l")
  points(sort(m4$Stime_resc),rev(100*(1:length(m4$Stime_resc)-1)/(length(m4$Stime_resc)-1)),col="gray",type="l")
  points(sort(m5$Stime_resc),rev(100*(1:length(m5$Stime_resc)-1)/(length(m5$Stime_resc)-1)),col="gray",type="l")
  points(sort(m6$Stime_resc),rev(100*(1:length(m6$Stime_resc)-1)/(length(m6$Stime_resc)-1)),col="gray",type="l")
  points(sort(m7$Stime_resc),rev(100*(1:length(m7$Stime_resc)-1)/(length(m7$Stime_resc)-1)),col="gray",type="l")
  points(sort(m8$Stime_resc),rev(100*(1:length(m8$Stime_resc)-1)/(length(m8$Stime_resc)-1)),col="gray",type="l")
  points(sort(m9$Stime_resc),rev(100*(1:length(m9$Stime_resc)-1)/(length(m9$Stime_resc)-1)),col="gray",type="l")
  points(sort(m10$Stime_resc),rev(100*(1:length(m10$Stime_resc)-1)/(length(m10$Stime_resc)-1)),col="gray",type="l")
  points(sort(m11$Stime_resc),rev(100*(1:length(m11$Stime_resc)-1)/(length(m11$Stime_resc)-1)),col="gray",type="l")
  points(sort(m12$Stime_resc),rev(100*(1:length(m12$Stime_resc)-1)/(length(m12$Stime_resc)-1)),col="gray",type="l")
  points(sort(m13$Stime_resc),rev(100*(1:length(m13$Stime_resc)-1)/(length(m13$Stime_resc)-1)),col="gray",type="l")
  points(sort(m14$Stime_resc),rev(100*(1:length(m14$Stime_resc)-1)/(length(m14$Stime_resc)-1)),col="gray",type="l")
  points(sort(m15$Stime_resc),rev(100*(1:length(m15$Stime_resc)-1)/(length(m15$Stime_resc)-1)),col="gray",type="l")
  points(sort(m16$Stime_resc),rev(100*(1:length(m16$Stime_resc)-1)/(length(m16$Stime_resc)-1)),col="gray",type="l")
  points(sort(m17$Stime_resc),rev(100*(1:length(m17$Stime_resc)-1)/(length(m17$Stime_resc)-1)),col="gray",type="l")
  points(sort(m18$Stime_resc),rev(100*(1:length(m18$Stime_resc)-1)/(length(m18$Stime_resc)-1)),col="gray",type="l")
  points(sort(m19$Stime_resc),rev(100*(1:length(m19$Stime_resc)-1)/(length(m19$Stime_resc)-1)),col="gray",type="l")
  points(sort(m20$Stime_resc),rev(100*(1:length(m20$Stime_resc)-1)/(length(m20$Stime_resc)-1)),col="gray",type="l")
  points(sort(mall$Stime_resc),rev(100*(1:length(mall$Stime_resc)-1)/(length(mall$Stime_resc)-1)),col="#A6761D",lwd=3,type="l")
  text(70,92,"Inbred lines",col="gray",adj=0,font=2,cex=1.2)
  text(70,85,"Pooled lines",adj=0,col="#A6761D",font=2,cex=1.2)
  
  # close device
  dev.off()
}
#-------------------------------------------------------------------------------
#saving the data of rescaled survival probabilities for heritability estimation
write.csv(df.p20,"../Outputs/1.1.1. Rescaled survival probability of DGRP lines pooled.csv", row.names = FALSE)
write.csv(df.f20,"../Outputs/1.1.2. Rescaled survival probability of DGRP lines females.csv",row.names = FALSE)
write.csv(df.m20,"../Outputs/1.1.3. Rescaled survival probability of DGRP lines males.csv", row.names = FALSE)

#saving session information with all packages versions for reproducibility
#purposes
sink("../Outputs/1.1.4. Survival probability of DGRP lines_R_session.txt")
sessionInfo()
sink()
################################################################################
############################ END OF SCRIPT #####################################
################################################################################