# ------------------------------------------------------------------------------
# Script to calculate survival probabilities of DGRP lines under normoxia

# Data generated by Felix P Leiva (e-mail: felixpleiva@gmail.com)
# Script created by Felix P Leiva (e-mail: felixpleiva@gmail.com)

# Cite as:

# Leiva FP, Santos M, Rezende EL, & Verberk WCEP. (2024). Paper data and code
# for: Genetic variation of heat tolerance in a model ectotherm: an approach
# using thermal death times curves. Zenodo. DOI will be available here

# Cleaning working space
rm(list=ls())

# check directory
getwd()

# Libraries
library(dplyr)

# ------------------------------------------------------------------------------
#Load data of the 20 DGRP lines
all.lines.21<-read.csv("../Outputs/0.1.1. Survival time of Drosophila melanogaster across DGRP lines.csv")

#stock as factor
str(all.lines.21)
all.lines.21$stock<-as.factor(all.lines.21$stock)

#transform minutes in log10-scale to minutes
all.lines.21$surv.time2<-as.numeric(10^(all.lines.21$surv.time))

# subset by sex
data_f<-subset(all.lines.21,sex=="female") #females
data_m<-subset(all.lines.21,sex=="male") #males

# mean and sd of survival time by sex
all.lines.21 %>%
  group_by(test.temp, sex) %>%
  summarise(
    mean_survival_time = round(mean(surv.time2), 3),
    sd_survival_time = round(sd(surv.time2), 3)
)
# mean and sd of survival time sex pooled
all.lines.21 %>%
  group_by(test.temp) %>%
  summarise(
    mean_survival_time = round(mean(surv.time2), 3),
    sd_survival_time = round(sd(surv.time2), 3)
)

#-------------------------------------------------------------------------------
# subset by stock
levels(data_f$stock)
# [1] "25180" "25182" "25190" "25192" "25198" "25201" "25203" "28135" "28141" "28153"
# [11] "28173" "28180" "28191" "28196" "28197" "28198" "28247" "28248" "28258" "29652"

# FEMALES

f.25180<-subset(data_f,stock=="25180")
f.25182<-subset(data_f,stock=="25182")
f.25190<-subset(data_f,stock=="25190")
f.25192<-subset(data_f,stock=="25192")
f.25198<-subset(data_f,stock=="25198")
f.25201<-subset(data_f,stock=="25201")
f.25203<-subset(data_f,stock=="25203")
f.28135<-subset(data_f,stock=="28135")
f.28141<-subset(data_f,stock=="28141")
f.28153<-subset(data_f,stock=="28153")
f.28173<-subset(data_f,stock=="28173")
f.28180<-subset(data_f,stock=="28180")
f.28191<-subset(data_f,stock=="28191")
f.28196<-subset(data_f,stock=="28196")
f.28197<-subset(data_f,stock=="28197")
f.28198<-subset(data_f,stock=="28198")
f.28247<-subset(data_f,stock=="28247")
f.28248<-subset(data_f,stock=="28248")
f.28258<-subset(data_f,stock=="28258")
f.29652<-subset(data_f,stock=="29652")

# MALES

m.25180<-subset(data_m,stock=="25180")
m.25182<-subset(data_m,stock=="25182")
m.25190<-subset(data_m,stock=="25190")
m.25192<-subset(data_m,stock=="25192")
m.25198<-subset(data_m,stock=="25198")
m.25201<-subset(data_m,stock=="25201")
m.25203<-subset(data_m,stock=="25203")
m.28135<-subset(data_m,stock=="28135")
m.28141<-subset(data_m,stock=="28141")
m.28153<-subset(data_m,stock=="28153")
m.28173<-subset(data_m,stock=="28173")
m.28180<-subset(data_m,stock=="28180")
m.28191<-subset(data_m,stock=="28191")
m.28196<-subset(data_m,stock=="28196")
m.28197<-subset(data_m,stock=="28197")
m.28198<-subset(data_m,stock=="28198")
m.28247<-subset(data_m,stock=="28247")
m.28248<-subset(data_m,stock=="28248")
m.28258<-subset(data_m,stock=="28258")
m.29652<-subset(data_m,stock=="29652")

# FIGURE 1

{
#pdf("../Outputs/Figure_2_Thermal_death_time_curves_DGRP_lines.pdf", width = 10, height = 5, useDingbats = FALSE)
jpeg("../Outputs/Figure_1_Thermal_death_time_curves_DGRP_lines.jpeg",width = 10,height = 5,units = "in",res = 600)  
par(mfrow=c(1,2),tcl=-0.4, family="serif",omi=c(0,0,0,0))

#females
# labels
labs= c("1","2","5","10","30","120","420")
xs= log10(c(1, 2, 5, 10, 30, 60*2, 60*7))

#TDT curves
par(mai=c(0.9, 0.9, 0.1, 0.1))
plot(surv.time ~ jitter(test.temp,0.5),xlim=c(35.6,39.4),ylim=c(0,3),cex.axis=1.2, cex.lab=1.4,yaxt="n",cex=1.4,pch=16,
     col="#4DAC2660",xlab="Test temperature (ºC)",ylab="Time (min)",
     data=f.25180)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25182)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25190)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25192)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25198)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25201)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.25203)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28135)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28141)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28153)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28173)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28180)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28191)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28196)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28197)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28198)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28247)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28248)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.28258)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#4DAC2660",data=f.29652)
abline(lm(surv.time ~ test.temp,data = f.25180),col="gray")
abline(lm(surv.time ~ test.temp,data = f.25182),col="gray")
abline(lm(surv.time ~ test.temp,data = f.25190),col="gray")
abline(lm(surv.time ~ test.temp,data = f.25192),col="gray")
abline(lm(surv.time ~ test.temp,data = f.25198),col="gray")
abline(lm(surv.time ~ test.temp,data = f.25201),col="gray")
abline(lm(surv.time ~ test.temp,data = f.25203),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28135),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28141),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28153),col="gray")	
abline(lm(surv.time ~ test.temp,data = f.28173),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28180),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28191),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28196),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28197),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28198),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28247),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28248),col="gray")
abline(lm(surv.time ~ test.temp,data = f.28258),col="gray")
abline(lm(surv.time ~ test.temp,data = f.29652),col="gray")
abline(lm(surv.time ~ test.temp,data = data_f),col="#4DAC26",lwd=3)

text(37.5,2.9,"Inbred lines",col="gray",adj=0,font=2,cex=1.2)
text(37.5,2.7,"Inbred lines pooled",adj=0,col="#4DAC26",font=2,cex=1.2)
text(36.0, 0.3, "\u2640", col = "#4DAC26", adj = 0, font = 2, cex = 3) # Female symbol
#update axis
axis(2, at=xs, labels=labs, cex.axis=1.2)
par(mai=c(0.55,0.6,0.1,0.1))
#-----------------------------------------------------------------------------
#males
# labels
labs= c("1","2","5","10","30","120","420")
xs= log10(c(1,2,5,10,30,60*2,60*7))

par(mai=c(0.9, 0.9, 0.1, 0.1))
plot(surv.time ~ jitter(test.temp,0.5),xlim=c(35.6,39.4),ylim=c(0,3),yaxt="n",
     cex.axis=1.2, cex.lab=1.4,cex=1.4,pch=16,col="#A6761D70",
     xlab="Test temperature (ºC)",ylab="Time (min)",
     data=m.25180)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25182)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25190)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25192)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25198)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25201)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.25203)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28135)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28141)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28153)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28173)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28180)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28191)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28196)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28197)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28198)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28247)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28248)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.28258)
points(surv.time ~ jitter(test.temp,0.5),cex=1.4,pch=16,col="#A6761D70",data=m.29652)
abline(lm(surv.time ~ test.temp,data = m.25180),col="gray")
abline(lm(surv.time ~ test.temp,data = m.25182),col="gray")
abline(lm(surv.time ~ test.temp,data = m.25190),col="gray")
abline(lm(surv.time ~ test.temp,data = m.25192),col="gray")
abline(lm(surv.time ~ test.temp,data = m.25198),col="gray")
abline(lm(surv.time ~ test.temp,data = m.25201),col="gray")
abline(lm(surv.time ~ test.temp,data = m.25203),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28135),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28141),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28153),col="gray")	
abline(lm(surv.time ~ test.temp,data = m.28173),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28180),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28191),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28196),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28197),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28198),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28247),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28248),col="gray")
abline(lm(surv.time ~ test.temp,data = m.28258),col="gray")
abline(lm(surv.time ~ test.temp,data = m.29652),col="gray")
abline(lm(surv.time ~ test.temp,data = data_m),col="#A6761D",lwd=3)


text(37.5,2.9,"Inbred lines",col="gray",adj=0,font=2,cex=1.2)
text(37.5,2.7,"Inbred lines pooled",adj=0,col="#A6761D",font=2,cex=1.2)
text(36.0, 0.3, "\u2642", col = "#A6761D", adj = 0, font = 2, cex = 3) # Male symbol

#update axis
axis(2, at=xs, labels=labs, cex.axis=1.2)

# close device
dev.off()
}

#saving session information with all packages versions for reproducibility
#purposes
sink("../Outputs/Plot_Figure_1_TDT_females_and_males_R_session.txt")
sessionInfo()
sink()
#--------------------------- END OF SCRIPT -------------------------------------