# ------------------------------------------------------------------------------
# Script to calculate broad-sense heritability (H^2)
# ------------------------------------------------------------------------------
# Data generated by Félix P Leiva (e-mail: felixpleiva@gmail.com) 
# Script created by Félix P Leiva (e-mail: felixpleiva@gmail.com)
# ------------------------------------------------------------------------------
# Cite as:

# Leiva FP, Santos M, Rezende E, & Verberk WCEP. (2022). Data and code of
# manuscript: Genetic variation on heat tolerance in a model ectotherm. Zenodo.
# (DOI is coming)
# ------------------------------------------------------------------------------
# Cleaning working space
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# ------------------------------------------------------------------------------
# set the working directory to the folder containing this script:
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
# ------------------------------------------------------------------------------
# check directory
getwd()
# ------------------------------------------------------------------------------
#Libraries
library(nlme)
# ------------------------------------------------------------------------------
#Load data
tdt<-read.csv("../Outputs/0.1.1. Survival time of Drosophila melanogaster across DGRP lines.csv")
# ------------------------------------------------------------------------------
#stock as factor
str(tdt)
tdt$stock<-as.factor(tdt$stock)
# ------------------------------------------------------------------------------
# subset by sex
data_f<-subset(tdt,sex=="female") #females
data_m<-subset(tdt,sex=="male") #males
#-------------------------------------------------------------------------------
# fit 0 estimate the random effect for line only
fit0<-lme(surv.time ~ 1, random=~1|stock, data=tdt)

# fit1 estimate the among-line variance after accounting for temperature

fit1<-lme(surv.time ~ test.temp, random=~1|stock, data=tdt)
summary(fit1)
var_Gene2<-as.numeric(VarCorr(fit1)[1,1])
var_Resid2<-as.numeric(VarCorr(fit1)[2,1])

# Estimate heritability as stock / (stock + residual + temperature) * 100
Herit2<-var_Gene2 / (var_Gene2 + var_Resid2) * 100
Herit2 #19.26856

# The residual (unexplained variance)
Unexpl.<-var_Resid2 / (var_Gene2 + var_Resid2) * 100
Unexpl.#80.73144

####### fit2 estimate among strain variance in response to temperature

fit2<-lme(surv.time ~ test.temp, random=~test.temp|stock, data=tdt)
summary(fit2)
anova(fit1, fit2)
# AIC drops through the floor, and improved LR

# Estimate the heritability conditional on the environment

# On the NF diet as Intercept / (Intercept + Residual)
var_NF<-as.numeric(VarCorr(fit2)[1,1])
residual_var<-as.numeric(VarCorr(fit2)[5,1])
HeritNF<-var_NF / (var_NF + residual_var) * 100
HeritNF

# var HCD <- (Intercept + HCD + 2cov)
diet_k<-2
var_HCD<-(as.numeric(VarCorr(fit2)[1,1]) + as.numeric(VarCorr(fit2)[2,1]) + 2 * as.numeric(VarCorr(fit2)[2,3]) * as.numeric(VarCorr(fit2)[1,2]) * as.numeric(VarCorr(fit2)[2,2]))
HeritHCD<-var_HCD / (var_HCD + residual_var) * 100
HeritHCD

# On the HFD: lme(ln_survival ~ relevel(diet, ref="HFD"), random=~relevel(diet, ref="HFD")|line, data=data)
var_HFD<-(as.numeric(VarCorr(fit2)[1,1]) + as.numeric(VarCorr(fit2)[3,1]) + 2 * as.numeric(VarCorr(fit2)[3,3]) * as.numeric(VarCorr(fit2)[1,2]) * as.numeric(VarCorr(fit2)[3,2]))
HeritHFD<-var_HFD / (var_HFD + residual_var) * 100
HeritHFD

# On the HPD: lme(ln_survival ~ relevel(diet, ref="HPD"), random=~relevel(diet, ref="HPD")|line, data=data)
var_HPD<-(as.numeric(VarCorr(fit2)[1,1]) + as.numeric(VarCorr(fit2)[4,1]) + 2 * as.numeric(VarCorr(fit2)[4,3]) * as.numeric(VarCorr(fit2)[1,2]) * as.numeric(VarCorr(fit2)[4,2]))
HeritHPD<-var_HPD / (var_HPD + residual_var) * 100
HeritHPD


round((summary(fit2)$adj.r.squared)*100,digits=3)#76.105
#-------------------------------------------------------------------------------
#saving session information with all packages versions for reproducibility
#purposes
sink("../Outputs/2.1.1. Heritability_TDT_R_session.txt")
sessionInfo()
sink()
################################################################################
############################ END OF SCRIPT #####################################
################################################################################